import { db } from '$lib/database';

export const regions: Region[] = [
	'dolnośląskie',
	'kujawsko-pomorskie',
	'lubelskie',
	'lubuskie',
	'łódzkie',
	'małopolskie',
	'mazowieckie',
	'opolskie',
	'podkarpackie',
	'podlaskie',
	'pomorskie',
	'śląskie',
	'świętokrzyskie',
	'warmińsko-mazurskie',
	'wielkopolskie',
	'zachodniopomorskie',
];

type Region =
	| 'dolnośląskie'
	| 'kujawsko-pomorskie'
	| 'lubelskie'
	| 'lubuskie'
	| 'łódzkie'
	| 'małopolskie'
	| 'mazowieckie'
	| 'opolskie'
	| 'podkarpackie'
	| 'podlaskie'
	| 'pomorskie'
	| 'śląskie'
	| 'świętokrzyskie'
	| 'warmińsko-mazurskie'
	| 'wielkopolskie'
	| 'zachodniopomorskie';

enum RodzajSzkoły {
	Liceum,
	Technikum,
}

type Books = string[] | { required?: string[]; optional: string[] };

type Option = Record<string, Choice>;

interface Choice {
	books: Books;
	options?: Record<string, Option>;
}

interface School {
	name: string;
	abbr: string;
	city: string;
	region: Region;
	type: 'liceum' | 'technikum';
	options: Record<string, Option>;
}

export const ALOPB: School = {
	name: 'Akademickie Liceum Ogólnokształcące Politechniki Białostockiej',
	abbr: 'ALOPB',
	city: 'Białystok',
	region: 'podlaskie',
	type: 'liceum',
	options: {
		Klasa: {
			'Klasa 1': {
				books: {
					required: [],
					optional: [],
				},
				options: {
					Profil: {
						'Przemysł przyszłości': {
							books: [],
						},
						'Architektura i budownictwo': {
							books: [],
						},
					},
					Język: {
						Niemiecki: {
							books: [],
						},
						Rosyjski: {
							books: {
								optional: [],
								required: [],
							},
						},
					},
				},
			},
			'Klasa 2': {
				books: {
					required: [],
					optional: [],
				},
				options: {
					Profil: {
						Robotyka: {
							books: [],
						},
						Programowanie: {
							books: [],
						},
					},
				},
			},
		},
	},
};

export const regionMap: Record<string, string[]> = {
	dolnośląskie: [
		'Wrocław',
		'Wałbrzych',
		'Legnica',
		'Jelenia Góra',
		'Lubin',
		'Głogów',
		'Świdnica',
		'Bolesławiec',
		'Oleśnica',
		'Dzierżoniów',
		'Oława',
		'Zgorzelec',
		'Bielawa',
		'Kłodzko',
		'Jawor',
		'Świebodzice',
		'Polkowice',
		'Nowa Ruda',
		'Lubań',
		'Kamienna Góra',
		'Bogatynia',
		'Strzegom',
		'Jelcz-Laskowice',
		'Złotoryja',
		'Boguszów-Gorce',
		'Ząbkowice Śląskie',
		'Chojnów',
		'Trzebnica',
		'Brzeg Dolny',
		'Strzelin',
		'Wołów',
		'Góra',
		'Milicz',
		'Kowary',
		'Syców',
		'Bystrzyca Kłodzka',
		'Kudowa-Zdrój',
		'Środa Śląska',
		'Oborniki Śląskie',
		'Lwówek Śląski',
		'Ziębice',
		'Chocianów',
		'Siechnice',
		'Pieszyce',
		'Sobótka',
		'Kąty Wrocławskie',
		'Żarów',
		'Twardogóra',
		'Gryfów Śląski',
		'Szklarska Poręba',
		'Piława Górna',
		'Żmigród',
		'Głuszyca',
		'Polanica-Zdrój',
		'Piechowice',
		'Przemków',
		'Lubawka',
		'Pieńsk',
		'Stronie Śląskie',
		'Lądek-Zdrój',
		'Szczawno-Zdrój',
		'Ścinawa',
		'Szczytna',
		'Jaworzyna Śląska',
		'Bolków',
		'Bierutów',
		'Jedlina-Zdrój',
		'Karpacz',
		'Duszniki-Zdrój',
		'Leśna',
		'Olszyna',
		'Nowogrodziec',
		'Zawidów',
		'Świeradów-Zdrój',
		'Mieroszów',
		'Mirsk',
		'Wojcieszów',
		'Prochowice',
		'Niemcza',
		'Węgliniec',
		'Złoty Stok',
		'Wąsosz',
		'Międzylesie',
		'Bardo',
		'Radków',
		'Międzybórz',
		'Świerzawa',
		'Wiązów',
		'Prusice',
		'Lubomierz',
		'Wleń',
		'Kamieniec Ząbkowicki',
	],
	'kujawsko-pomorskie': [
		'Bydgoszcz',
		'Toruń',
		'Włocławek',
		'Grudziądz',
		'Inowrocław',
		'Brodnica',
		'Świecie',
		'Chełmno',
		'Nakło nad Notecią',
		'Rypin',
		'Solec Kujawski',
		'Chełmża',
		'Lipno',
		'Żnin',
		'Tuchola',
		'Wąbrzeźno',
		'Golub-Dobrzyń',
		'Aleksandrów Kujawski',
		'Mogilno',
		'Koronowo',
		'Ciechocinek',
		'Szubin',
		'Sępólno Krajeńskie',
		'Kruszwica',
		'Janikowo',
		'Barcin',
		'Gniewkowo',
		'Więcbork',
		'Nowe',
		'Pakość',
		'Strzelno',
		'Radziejów',
		'Kcynia',
		'Brześć Kujawski',
		'Łabiszyn',
		'Piotrków Kujawski',
		'Mrocza',
		'Kowalewo Pomorskie',
		'Janowiec Wielkopolski',
		'Jabłonowo Pomorskie',
		'Skępe',
		'Kowal',
		'Łasin',
		'Lubraniec',
		'Izbica Kujawska',
		'Kamień Krajeński',
		'Dobrzyń nad Wisłą',
		'Chodecz',
		'Nieszawa',
		'Radzyń Chełmiński',
		'Lubień Kujawski',
		'Górzno',
		'Pruszcz',
	],
	lubelskie: [
		'Lublin',
		'Zamość',
		'Chełm',
		'Biała Podlaska',
		'Puławy',
		'Świdnik',
		'Kraśnik',
		'Łuków',
		'Biłgoraj',
		'Lubartów',
		'Tomaszów Lubelski',
		'Łęczna',
		'Krasnystaw',
		'Hrubieszów',
		'Międzyrzec Podlaski',
		'Dęblin',
		'Radzyń Podlaski',
		'Włodawa',
		'Janów Lubelski',
		'Parczew',
		'Ryki',
		'Poniatowa',
		'Opole Lubelskie',
		'Bełżyce',
		'Terespol',
		'Szczebrzeszyn',
		'Bychawa',
		'Rejowiec Fabryczny',
		'Nałęczów',
		'Tarnogród',
		'Kock',
		'Zwierzyniec',
		'Krasnobród',
		'Kazimierz Dolny',
		'Piaski',
		'Stoczek Łukowski',
		'Annopol',
		'Józefów',
		'Lubycza Królewska',
		'Łaszczów',
		'Tyszowce',
		'Ostrów Lubelski',
		'Rejowiec',
		'Urzędów',
		'Modliborzyce',
		'Frampol',
		'Siedliszcze',
		'Józefów nad Wisłą',
		'Goraj',
		'Izbica',
		'Kamionka',
	],
	lubuskie: [
		'Zielona Góra',
		'Gorzów Wielkopolski',
		'Nowa Sól',
		'Żary',
		'Żagań',
		'Świebodzin',
		'Międzyrzecz',
		'Kostrzyn nad Odrą',
		'Sulechów',
		'Słubice',
		'Gubin',
		'Lubsko',
		'Wschowa',
		'Szprotawa',
		'Krosno Odrzańskie',
		'Drezdenko',
		'Sulęcin',
		'Strzelce Krajeńskie',
		'Skwierzyna',
		'Kożuchów',
		'Witnica',
		'Rzepin',
		'Nowogród Bobrzański',
		'Zbąszynek',
		'Bytom Odrzański',
		'Jasień',
		'Sława',
		'Czerwieńsk',
		'Ośno Lubuskie',
		'Babimost',
		'Iłowa',
		'Kargowa',
		'Małomice',
		'Dobiegniew',
		'Gozdnica',
		'Nowe Miasteczko',
		'Cybinka',
		'Torzym',
		'Łęknica',
		'Trzciel',
		'Lubniewice',
		'Otyń',
		'Szlichtyngowa',
	],
	łódzkie: [
		'Łódź',
		'Piotrków Trybunalski',
		'Pabianice',
		'Tomaszów Mazowiecki',
		'Bełchatów',
		'Zgierz',
		'Skierniewice',
		'Radomsko',
		'Kutno',
		'Sieradz',
		'Zduńska Wola',
		'Łowicz',
		'Wieluń',
		'Aleksandrów Łódzki',
		'Opoczno',
		'Ozorków',
		'Konstantynów Łódzki',
		'Rawa Mazowiecka',
		'Łask',
		'Głowno',
		'Łęczyca',
		'Koluszki',
		'Brzeziny',
		'Wieruszów',
		'Żychlin',
		'Zelów',
		'Poddębice',
		'Tuszyn',
		'Pajęczno',
		'Sulejów',
		'Działoszyn',
		'Krośniewice',
		'Drzewica',
		'Przedbórz',
		'Stryków',
		'Rzgów',
		'Złoczew',
		'Warta',
		'Biała Rawska',
		'Uniejów',
		'Kamieńsk',
		'Wolbórz',
		'Błaszki',
		'Szadek',
		'Piątek',
		'Lutomiersk',
		'Bolimów',
		'Lututów',
	],
	małopolskie: [
		'Kraków',
		'Tarnów',
		'Nowy Sącz',
		'Oświęcim',
		'Chrzanów',
		'Olkusz',
		'Nowy Targ',
		'Bochnia',
		'Gorlice',
		'Zakopane',
		'Skawina',
		'Wieliczka',
		'Andrychów',
		'Trzebinia',
		'Wadowice',
		'Kęty',
		'Myślenice',
		'Libiąż',
		'Brzesko',
		'Limanowa',
		'Niepołomice',
		'Rabka-Zdrój',
		'Dąbrowa Tarnowska',
		'Miechów',
		'Brzeszcze',
		'Krynica-Zdrój',
		'Bukowno',
		'Krzeszowice',
		'Sucha Beskidzka',
		'Chełmek',
		'Stary Sącz',
		'Wolbrom',
		'Mszana Dolna',
		'Tuchów',
		'Sułkowice',
		'Dobczyce',
		'Grybów',
		'Proszowice',
		'Piwniczna-Zdrój',
		'Maków Podhalański',
		'Szczawnica',
		'Jordanów',
		'Muszyna',
		'Biecz',
		'Kalwaria Zebrzydowska',
		'Słomniki',
		'Żabno',
		'Szczucin',
		'Skała',
		'Zator',
		'Alwernia',
		'Wojnicz',
		'Bobowa',
		'Ryglice',
		'Radłów',
		'Nowy Wiśnicz',
		'Ciężkowice',
		'Świątniki Górne',
		'Czchów',
		'Nowe Brzesko',
		'Zakliczyn',
		'Koszyce',
	],
	mazowieckie: [
		'Warszawa',
		'Radom',
		'Płock',
		'Siedlce',
		'Pruszków',
		'Legionowo',
		'Ostrołęka',
		'Piaseczno',
		'Otwock',
		'Ciechanów',
		'Mińsk Mazowiecki',
		'Żyrardów',
		'Wołomin',
		'Ząbki',
		'Sochaczew',
		'Marki',
		'Grodzisk Mazowiecki',
		'Mława',
		'Nowy Dwór Mazowiecki',
		'Wyszków',
		'Kobyłka',
		'Piastów',
		'Ostrów Mazowiecka',
		'Płońsk',
		'Józefów',
		'Sulejówek',
		'Pułtusk',
		'Sokołów Podlaski',
		'Gostynin',
		'Pionki',
		'Sierpc',
		'Zielonka',
		'Garwolin',
		'Kozienice',
		'Przasnysz',
		'Konstancin-Jeziorna',
		'Łomianki',
		'Grójec',
		'Milanówek',
		'Brwinów',
		'Radzymin',
		'Węgrów',
		'Błonie',
		'Góra Kalwaria',
		'Warka',
		'Szydłowiec',
		'Ożarów Mazowiecki',
		'Karczew',
		'Maków Mazowiecki',
		'Żuromin',
		'Tłuszcz',
		'Zwoleń',
		'Nasielsk',
		'Łosice',
		'Białobrzegi',
		'Łochów',
		'Mszczonów',
		'Przysucha',
		'Lipsko',
		'Łaskarzew',
		'Iłża',
		'Pilawa',
		'Raciąż',
		'Serock',
		'Skaryszew',
		'Tarczyn',
		'Gąbin',
		'Żelechów',
		'Podkowa Leśna',
		'Nowe Miasto nad Pilicą',
		'Halinów',
		'Mrozy',
		'Myszyniec',
		'Zakroczym',
		'Chorzele',
		'Glinojeck',
		'Kałuszyn',
		'Drobin',
		'Różan',
		'Wyszogród',
		'Mogielnica',
		'Kosów Lacki',
		'Sanniki',
		'Brok',
		'Bieżuń',
		'Mordy',
		'Wyśmierzyce',
		'Solec nad Wisłą',
		'Cegłów',
		'Czerwińsk nad Wisłą',
		'Nowe Miasto',
		'Sochocin',
		'Jedlnia-Letnisko',
		'Lubowidz',
		'Wiskitki',
	],
	opolskie: [
		'Opole',
		'Kędzierzyn-Koźle',
		'Nysa',
		'Brzeg',
		'Kluczbork',
		'Prudnik',
		'Strzelce Opolskie',
		'Namysłów',
		'Krapkowice',
		'Głuchołazy',
		'Głubczyce',
		'Zdzieszowice',
		'Olesno',
		'Ozimek',
		'Grodków',
		'Praszka',
		'Paczków',
		'Zawadzkie',
		'Gogolin',
		'Otmuchów',
		'Niemodlin',
		'Kietrz',
		'Wołczyn',
		'Lewin Brzeski',
		'Głogówek',
		'Tułowice',
		'Dobrodzień',
		'Byczyna',
		'Kolonowskie',
		'Baborów',
		'Prószków',
		'Leśnica',
		'Gorzów Śląski',
		'Biała',
		'Korfantów',
		'Ujazd',
	],
	podkarpackie: [
		'Rzeszów',
		'Przemyśl',
		'Stalowa Wola',
		'Mielec',
		'Tarnobrzeg',
		'Krosno',
		'Dębica',
		'Jarosław',
		'Sanok',
		'Jasło',
		'Łańcut',
		'Ropczyce',
		'Przeworsk',
		'Nisko',
		'Leżajsk',
		'Lubaczów',
		'Nowa Dęba',
		'Kolbuszowa',
		'Ustrzyki Dolne',
		'Strzyżów',
		'Sędziszów Małopolski',
		'Brzozów',
		'Rudnik nad Sanem',
		'Głogów Małopolski',
		'Dynów',
		'Boguchwała',
		'Nowa Sarzyna',
		'Jedlicze',
		'Lesko',
		'Radymno',
		'Zagórz',
		'Pilzno',
		'Sokołów Małopolski',
		'Rymanów',
		'Tyczyn',
		'Pruchnik',
		'Radomyśl Wielki',
		'Kańczuga',
		'Zaklików',
		'Oleszyce',
		'Brzostek',
		'Błażowa',
		'Sieniawa',
		'Dukla',
		'Narol',
		'Cieszanów',
		'Iwonicz-Zdrój',
		'Przecław',
		'Baranów Sandomierski',
		'Ulanów',
		'Kołaczyce',
		'Dubiecko',
	],
	podlaskie: [
		'Białystok',
		'Suwałki',
		'Łomża',
		'Augustów',
		'Bielsk Podlaski',
		'Zambrów',
		'Grajewo',
		'Hajnówka',
		'Sokółka',
		'Łapy',
		'Siemiatycze',
		'Wasilków',
		'Kolno',
		'Mońki',
		'Wysokie Mazowieckie',
		'Czarna Białostocka',
		'Choroszcz',
		'Dąbrowa Białostocka',
		'Sejny',
		'Ciechanowiec',
		'Supraśl',
		'Brańsk',
		'Szczuczyn',
		'Michałowo',
		'Knyszyn',
		'Czyżew',
		'Zabłudów',
		'Krynki',
		'Lipsk',
		'Stawiski',
		'Suchowola',
		'Szepietowo',
		'Nowogród',
		'Drohiczyn',
		'Tykocin',
		'Goniądz',
		'Jedwabne',
		'Rajgród',
		'Kleszczele',
		'Suraż',
	],
	pomorskie: [
		'Gdańsk',
		'Gdynia',
		'Słupsk',
		'Tczew',
		'Wejherowo',
		'Rumia',
		'Starogard Gdański',
		'Chojnice',
		'Malbork',
		'Kwidzyn',
		'Sopot',
		'Lębork',
		'Pruszcz Gdański',
		'Reda',
		'Kościerzyna',
		'Bytów',
		'Ustka',
		'Kartuzy',
		'Człuchów',
		'Puck',
		'Miastko',
		'Sztum',
		'Władysławowo',
		'Nowy Dwór Gdański',
		'Czersk',
		'Prabuty',
		'Pelplin',
		'Skarszewy',
		'Gniew',
		'Żukowo',
		'Czarne',
		'Dzierzgoń',
		'Brusy',
		'Debrzno',
		'Nowy Staw',
		'Łeba',
		'Skórcz',
		'Kępice',
		'Hel',
		'Czarna Woda',
		'Jastarnia',
		'Krynica Morska',
	],
	śląskie: [
		'Katowice',
		'Częstochowa',
		'Sosnowiec',
		'Gliwice',
		'Zabrze',
		'Bielsko-Biała',
		'Bytom',
		'Rybnik',
		'Ruda Śląska',
		'Tychy',
		'Dąbrowa Górnicza',
		'Chorzów',
		'Jaworzno',
		'Jastrzębie-Zdrój',
		'Mysłowice',
		'Siemianowice Śląskie',
		'Żory',
		'Tarnowskie Góry',
		'Będzin',
		'Piekary Śląskie',
		'Racibórz',
		'Świętochłowice',
		'Zawiercie',
		'Wodzisław Śląski',
		'Mikołów',
		'Knurów',
		'Czechowice-Dziedzice',
		'Cieszyn',
		'Myszków',
		'Czeladź',
		'Żywiec',
		'Czerwionka-Leszczyny',
		'Pszczyna',
		'Lubliniec',
		'Łaziska Górne',
		'Rydułtowy',
		'Orzesze',
		'Bieruń',
		'Pyskowice',
		'Radlin',
		'Lędziny',
		'Radzionków',
		'Ustroń',
		'Skoczów',
		'Pszów',
		'Kłobuck',
		'Wisła',
		'Blachownia',
		'Imielin',
		'Wojkowice',
		'Kalety',
		'Poręba',
		'Miasteczko Śląskie',
		'Sławków',
		'Łazy',
		'Koniecpol',
		'Szczyrk',
		'Siewierz',
		'Kuźnia Raciborska',
		'Żarki',
		'Krzepice',
		'Woźniki',
		'Ogrodzieniec',
		'Strumień',
		'Szczekociny',
		'Toszek',
		'Wilamowice',
		'Koziegłowy',
		'Krzanowice',
		'Pilica',
		'Sośnicowice',
		'Olsztyn',
	],
	świętokrzyskie: [
		'Kielce',
		'Ostrowiec Świętokrzyski',
		'Starachowice',
		'Skarżysko-Kamienna',
		'Sandomierz',
		'Końskie',
		'Busko-Zdrój',
		'Jędrzejów',
		'Staszów',
		'Pińczów',
		'Włoszczowa',
		'Suchedniów',
		'Połaniec',
		'Opatów',
		'Sędziszów',
		'Stąporków',
		'Kazimierza Wielka',
		'Ożarów',
		'Chęciny',
		'Małogoszcz',
		'Chmielnik',
		'Radoszyce',
		'Ćmielów',
		'Kunów',
		'Daleszyce',
		'Wąchock',
		'Koprzywnica',
		'Bodzentyn',
		'Osiek',
		'Zawichost',
		'Morawica',
		'Łagów',
		'Stopnica',
		'Skalbmierz',
		'Działoszyce',
		'Wiślica',
		'Nowy Korczyn',
		'Pacanów',
		'Wodzisław',
		'Opatowiec',
		'Nowa Słupia',
		'Pierzchnica',
		'Iwaniska',
		'Klimontów',
		'Oleśnica',
		'Szydłów',
	],
	'warmińsko-mazurskie': [
		'Olsztyn',
		'Elbląg',
		'Ełk',
		'Iława',
		'Ostróda',
		'Giżycko',
		'Kętrzyn',
		'Bartoszyce',
		'Szczytno',
		'Mrągowo',
		'Działdowo',
		'Pisz',
		'Braniewo',
		'Olecko',
		'Lidzbark Warmiński',
		'Morąg',
		'Nidzica',
		'Gołdap',
		'Pasłęk',
		'Węgorzewo',
		'Nowe Miasto Lubawskie',
		'Biskupiec',
		'Lubawa',
		'Dobre Miasto',
		'Orneta',
		'Lidzbark',
		'Olsztynek',
		'Barczewo',
		'Orzysz',
		'Susz',
		'Reszel',
		'Ruciane-Nida',
		'Korsze',
		'Biała Piska',
		'Górowo Iławeckie',
		'Mikołajki',
		'Jeziorany',
		'Ryn',
		'Pieniężno',
		'Tolkmicko',
		'Miłakowo',
		'Pasym',
		'Miłomłyn',
		'Bisztynek',
		'Frombork',
		'Zalewo',
		'Kisielice',
		'Sępopol',
		'Młynary',
		'Wielbark',
	],
	wielkopolskie: [
		'Poznań',
		'Kalisz',
		'Konin',
		'Piła',
		'Ostrów Wielkopolski',
		'Gniezno',
		'Leszno',
		'Luboń',
		'Września',
		'Swarzędz',
		'Śrem',
		'Krotoszyn',
		'Turek',
		'Jarocin',
		'Wągrowiec',
		'Kościan',
		'Środa Wielkopolska',
		'Koło',
		'Rawicz',
		'Gostyń',
		'Szamotuły',
		'Chodzież',
		'Złotów',
		'Oborniki',
		'Pleszew',
		'Trzcianka',
		'Grodzisk Wielkopolski',
		'Nowy Tomyśl',
		'Ostrzeszów',
		'Kępno',
		'Mosina',
		'Słupca',
		'Wolsztyn',
		'Wronki',
		'Rogoźno',
		'Czarnków',
		'Międzychód',
		'Murowana Goślina',
		'Puszczykowo',
		'Kostrzyn',
		'Opalenica',
		'Pobiedziska',
		'Jastrowie',
		'Pniewy',
		'Witkowo',
		'Kórnik',
		'Trzemeszno',
		'Zbąszyń',
		'Koźmin Wielkopolski',
		'Kłodawa',
		'Krzyż Wielkopolski',
		'Buk',
		'Sieraków',
		'Stęszew',
		'Wieleń',
		'Śmigiel',
		'Czempiń',
		'Wyrzysk',
		'Odolanów',
		'Nowe Skalmierzyce',
		'Zduny',
		'Golina',
		'Skoki',
		'Krobia',
		'Szamocin',
		'Kleczew',
		'Okonek',
		'Nekla',
		'Ujście',
		'Opatówek',
		'Krajenka',
		'Rakoniewice',
		'Miłosław',
		'Sompolno',
		'Gołańcz',
		'Tuliszków',
		'Kobylin',
		'Miejska Górka',
		'Ślesin',
		'Pyzdry',
		'Dobrzyca',
		'Margonin',
		'Zagórów',
		'Lwówek',
		'Łobżenica',
		'Bojanowo',
		'Sulmierzyce',
		'Rydzyna',
		'Poniec',
		'Książ Wielkopolski',
		'Czerniejewo',
		'Wysoka',
		'Kłecko',
		'Borek Wielkopolski',
		'Rychwał',
		'Obrzycko',
		'Osieczna',
		'Żerków',
		'Pogorzela',
		'Raszków',
		'Dąbie',
		'Jutrosin',
		'Grabów nad Prosną',
		'Ostroróg',
		'Mikstat',
		'Chocz',
		'Wielichowo',
		'Krzywiń',
		'Przedecz',
		'Dolsk',
		'Stawiszyn',
		'Jaraczewo',
		'Dobra',
		'Budzyń',
		'Koźminek',
		'Kaczory',
	],
	zachodniopomorskie: [
		'Szczecin',
		'Koszalin',
		'Stargard',
		'Kołobrzeg',
		'Świnoujście',
		'Szczecinek',
		'Police',
		'Wałcz',
		'Białogard',
		'Goleniów',
		'Gryfino',
		'Nowogard',
		'Gryfice',
		'Świdwin',
		'Choszczno',
		'Dębno',
		'Barlinek',
		'Darłowo',
		'Złocieniec',
		'Pyrzyce',
		'Sławno',
		'Drawsko Pomorskie',
		'Myślibórz',
		'Łobez',
		'Trzebiatów',
		'Kamień Pomorski',
		'Połczyn-Zdrój',
		'Chojna',
		'Czaplinek',
		'Sianów',
		'Karlino',
		'Międzyzdroje',
		'Borne Sulinowo',
		'Wolin',
		'Kalisz Pomorski',
		'Resko',
		'Bobolice',
		'Płoty',
		'Lipiany',
		'Barwice',
		'Mieszkowice',
		'Maszewo',
		'Chociwel',
		'Mirosławiec',
		'Mielno',
		'Polanów',
		'Recz',
		'Węgorzyno',
		'Dziwnów',
		'Golczewo',
		'Pełczyce',
		'Tychowo',
		'Stepnica',
		'Gościno',
		'Człopa',
		'Dobra',
		'Drawno',
		'Trzcińsko-Zdrój',
		'Dobrzany',
		'Biały Bór',
		'Ińsko',
		'Tuczno',
		'Moryń',
		'Cedynia',
		'Suchań',
		'Nowe Warpno',
	],
};

export const cities = [
	'Wrocław',
	'Wałbrzych',
	'Legnica',
	'Jelenia Góra',
	'Lubin',
	'Głogów',
	'Świdnica',
	'Bolesławiec',
	'Oleśnica',
	'Dzierżoniów',
	'Oława',
	'Zgorzelec',
	'Bielawa',
	'Kłodzko',
	'Jawor',
	'Świebodzice',
	'Polkowice',
	'Nowa Ruda',
	'Lubań',
	'Kamienna Góra',
	'Bogatynia',
	'Strzegom',
	'Jelcz-Laskowice',
	'Złotoryja',
	'Boguszów-Gorce',
	'Ząbkowice Śląskie',
	'Chojnów',
	'Trzebnica',
	'Brzeg Dolny',
	'Strzelin',
	'Wołów',
	'Góra',
	'Milicz',
	'Kowary',
	'Syców',
	'Bystrzyca Kłodzka',
	'Kudowa-Zdrój',
	'Środa Śląska',
	'Oborniki Śląskie',
	'Lwówek Śląski',
	'Ziębice',
	'Chocianów',
	'Siechnice',
	'Pieszyce',
	'Sobótka',
	'Kąty Wrocławskie',
	'Żarów',
	'Twardogóra',
	'Gryfów Śląski',
	'Szklarska Poręba',
	'Piława Górna',
	'Żmigród',
	'Głuszyca',
	'Polanica-Zdrój',
	'Piechowice',
	'Przemków',
	'Lubawka',
	'Pieńsk',
	'Stronie Śląskie',
	'Lądek-Zdrój',
	'Szczawno-Zdrój',
	'Ścinawa',
	'Szczytna',
	'Jaworzyna Śląska',
	'Bolków',
	'Bierutów',
	'Jedlina-Zdrój',
	'Karpacz',
	'Duszniki-Zdrój',
	'Leśna',
	'Olszyna',
	'Nowogrodziec',
	'Zawidów',
	'Świeradów-Zdrój',
	'Mieroszów',
	'Mirsk',
	'Wojcieszów',
	'Prochowice',
	'Niemcza',
	'Węgliniec',
	'Złoty Stok',
	'Wąsosz',
	'Międzylesie',
	'Bardo',
	'Radków',
	'Międzybórz',
	'Świerzawa',
	'Wiązów',
	'Prusice',
	'Lubomierz',
	'Wleń',
	'Kamieniec Ząbkowicki',
	'Bydgoszcz',
	'Toruń',
	'Włocławek',
	'Grudziądz',
	'Inowrocław',
	'Brodnica',
	'Świecie',
	'Chełmno',
	'Nakło nad Notecią',
	'Rypin',
	'Solec Kujawski',
	'Chełmża',
	'Lipno',
	'Żnin',
	'Tuchola',
	'Wąbrzeźno',
	'Golub-Dobrzyń',
	'Aleksandrów Kujawski',
	'Mogilno',
	'Koronowo',
	'Ciechocinek',
	'Szubin',
	'Sępólno Krajeńskie',
	'Kruszwica',
	'Janikowo',
	'Barcin',
	'Gniewkowo',
	'Więcbork',
	'Nowe',
	'Pakość',
	'Strzelno',
	'Radziejów',
	'Kcynia',
	'Brześć Kujawski',
	'Łabiszyn',
	'Piotrków Kujawski',
	'Mrocza',
	'Kowalewo Pomorskie',
	'Janowiec Wielkopolski',
	'Jabłonowo Pomorskie',
	'Skępe',
	'Kowal',
	'Łasin',
	'Lubraniec',
	'Izbica Kujawska',
	'Kamień Krajeński',
	'Dobrzyń nad Wisłą',
	'Chodecz',
	'Nieszawa',
	'Radzyń Chełmiński',
	'Lubień Kujawski',
	'Górzno',
	'Pruszcz',
	'Lublin',
	'Zamość',
	'Chełm',
	'Biała Podlaska',
	'Puławy',
	'Świdnik',
	'Kraśnik',
	'Łuków',
	'Biłgoraj',
	'Lubartów',
	'Tomaszów Lubelski',
	'Łęczna',
	'Krasnystaw',
	'Hrubieszów',
	'Międzyrzec Podlaski',
	'Dęblin',
	'Radzyń Podlaski',
	'Włodawa',
	'Janów Lubelski',
	'Parczew',
	'Ryki',
	'Poniatowa',
	'Opole Lubelskie',
	'Bełżyce',
	'Terespol',
	'Szczebrzeszyn',
	'Bychawa',
	'Rejowiec Fabryczny',
	'Nałęczów',
	'Tarnogród',
	'Kock',
	'Zwierzyniec',
	'Krasnobród',
	'Kazimierz Dolny',
	'Piaski',
	'Stoczek Łukowski',
	'Annopol',
	'Józefów',
	'Lubycza Królewska',
	'Łaszczów',
	'Tyszowce',
	'Ostrów Lubelski',
	'Rejowiec',
	'Urzędów',
	'Modliborzyce',
	'Frampol',
	'Siedliszcze',
	'Józefów nad Wisłą',
	'Goraj',
	'Izbica',
	'Kamionka',
	'Zielona Góra',
	'Gorzów Wielkopolski',
	'Nowa Sól',
	'Żary',
	'Żagań',
	'Świebodzin',
	'Międzyrzecz',
	'Kostrzyn nad Odrą',
	'Sulechów',
	'Słubice',
	'Gubin',
	'Lubsko',
	'Wschowa',
	'Szprotawa',
	'Krosno Odrzańskie',
	'Drezdenko',
	'Sulęcin',
	'Strzelce Krajeńskie',
	'Skwierzyna',
	'Kożuchów',
	'Witnica',
	'Rzepin',
	'Nowogród Bobrzański',
	'Zbąszynek',
	'Bytom Odrzański',
	'Jasień',
	'Sława',
	'Czerwieńsk',
	'Ośno Lubuskie',
	'Babimost',
	'Iłowa',
	'Kargowa',
	'Małomice',
	'Dobiegniew',
	'Gozdnica',
	'Nowe Miasteczko',
	'Cybinka',
	'Torzym',
	'Łęknica',
	'Trzciel',
	'Lubniewice',
	'Otyń',
	'Szlichtyngowa',
	'Łódź',
	'Piotrków Trybunalski',
	'Pabianice',
	'Tomaszów Mazowiecki',
	'Bełchatów',
	'Zgierz',
	'Skierniewice',
	'Radomsko',
	'Kutno',
	'Sieradz',
	'Zduńska Wola',
	'Łowicz',
	'Wieluń',
	'Aleksandrów Łódzki',
	'Opoczno',
	'Ozorków',
	'Konstantynów Łódzki',
	'Rawa Mazowiecka',
	'Łask',
	'Głowno',
	'Łęczyca',
	'Koluszki',
	'Brzeziny',
	'Wieruszów',
	'Żychlin',
	'Zelów',
	'Poddębice',
	'Tuszyn',
	'Pajęczno',
	'Sulejów',
	'Działoszyn',
	'Krośniewice',
	'Drzewica',
	'Przedbórz',
	'Stryków',
	'Rzgów',
	'Złoczew',
	'Warta',
	'Biała Rawska',
	'Uniejów',
	'Kamieńsk',
	'Wolbórz',
	'Błaszki',
	'Szadek',
	'Piątek',
	'Lutomiersk',
	'Bolimów',
	'Lututów',
	'Kraków',
	'Tarnów',
	'Nowy Sącz',
	'Oświęcim',
	'Chrzanów',
	'Olkusz',
	'Nowy Targ',
	'Bochnia',
	'Gorlice',
	'Zakopane',
	'Skawina',
	'Wieliczka',
	'Andrychów',
	'Trzebinia',
	'Wadowice',
	'Kęty',
	'Myślenice',
	'Libiąż',
	'Brzesko',
	'Limanowa',
	'Niepołomice',
	'Rabka-Zdrój',
	'Dąbrowa Tarnowska',
	'Miechów',
	'Brzeszcze',
	'Krynica-Zdrój',
	'Bukowno',
	'Krzeszowice',
	'Sucha Beskidzka',
	'Chełmek',
	'Stary Sącz',
	'Wolbrom',
	'Mszana Dolna',
	'Tuchów',
	'Sułkowice',
	'Dobczyce',
	'Grybów',
	'Proszowice',
	'Piwniczna-Zdrój',
	'Maków Podhalański',
	'Szczawnica',
	'Jordanów',
	'Muszyna',
	'Biecz',
	'Kalwaria Zebrzydowska',
	'Słomniki',
	'Żabno',
	'Szczucin',
	'Skała',
	'Zator',
	'Alwernia',
	'Wojnicz',
	'Bobowa',
	'Ryglice',
	'Radłów',
	'Nowy Wiśnicz',
	'Ciężkowice',
	'Świątniki Górne',
	'Czchów',
	'Nowe Brzesko',
	'Zakliczyn',
	'Koszyce',
	'Warszawa',
	'Radom',
	'Płock',
	'Siedlce',
	'Pruszków',
	'Legionowo',
	'Ostrołęka',
	'Piaseczno',
	'Otwock',
	'Ciechanów',
	'Mińsk Mazowiecki',
	'Żyrardów',
	'Wołomin',
	'Ząbki',
	'Sochaczew',
	'Marki',
	'Grodzisk Mazowiecki',
	'Mława',
	'Nowy Dwór Mazowiecki',
	'Wyszków',
	'Kobyłka',
	'Piastów',
	'Ostrów Mazowiecka',
	'Płońsk',
	'Józefów',
	'Sulejówek',
	'Pułtusk',
	'Sokołów Podlaski',
	'Gostynin',
	'Pionki',
	'Sierpc',
	'Zielonka',
	'Garwolin',
	'Kozienice',
	'Przasnysz',
	'Konstancin-Jeziorna',
	'Łomianki',
	'Grójec',
	'Milanówek',
	'Brwinów',
	'Radzymin',
	'Węgrów',
	'Błonie',
	'Góra Kalwaria',
	'Warka',
	'Szydłowiec',
	'Ożarów Mazowiecki',
	'Karczew',
	'Maków Mazowiecki',
	'Żuromin',
	'Tłuszcz',
	'Zwoleń',
	'Nasielsk',
	'Łosice',
	'Białobrzegi',
	'Łochów',
	'Mszczonów',
	'Przysucha',
	'Lipsko',
	'Łaskarzew',
	'Iłża',
	'Pilawa',
	'Raciąż',
	'Serock',
	'Skaryszew',
	'Tarczyn',
	'Gąbin',
	'Żelechów',
	'Podkowa Leśna',
	'Nowe Miasto nad Pilicą',
	'Halinów',
	'Mrozy',
	'Myszyniec',
	'Zakroczym',
	'Chorzele',
	'Glinojeck',
	'Kałuszyn',
	'Drobin',
	'Różan',
	'Wyszogród',
	'Mogielnica',
	'Kosów Lacki',
	'Sanniki',
	'Brok',
	'Bieżuń',
	'Mordy',
	'Wyśmierzyce',
	'Solec nad Wisłą',
	'Cegłów',
	'Czerwińsk nad Wisłą',
	'Nowe Miasto',
	'Sochocin',
	'Jedlnia-Letnisko',
	'Lubowidz',
	'Wiskitki',
	'Opole',
	'Kędzierzyn-Koźle',
	'Nysa',
	'Brzeg',
	'Kluczbork',
	'Prudnik',
	'Strzelce Opolskie',
	'Namysłów',
	'Krapkowice',
	'Głuchołazy',
	'Głubczyce',
	'Zdzieszowice',
	'Olesno',
	'Ozimek',
	'Grodków',
	'Praszka',
	'Paczków',
	'Zawadzkie',
	'Gogolin',
	'Otmuchów',
	'Niemodlin',
	'Kietrz',
	'Wołczyn',
	'Lewin Brzeski',
	'Głogówek',
	'Tułowice',
	'Dobrodzień',
	'Byczyna',
	'Kolonowskie',
	'Baborów',
	'Prószków',
	'Leśnica',
	'Gorzów Śląski',
	'Biała',
	'Korfantów',
	'Ujazd',
	'Rzeszów',
	'Przemyśl',
	'Stalowa Wola',
	'Mielec',
	'Tarnobrzeg',
	'Krosno',
	'Dębica',
	'Jarosław',
	'Sanok',
	'Jasło',
	'Łańcut',
	'Ropczyce',
	'Przeworsk',
	'Nisko',
	'Leżajsk',
	'Lubaczów',
	'Nowa Dęba',
	'Kolbuszowa',
	'Ustrzyki Dolne',
	'Strzyżów',
	'Sędziszów Małopolski',
	'Brzozów',
	'Rudnik nad Sanem',
	'Głogów Małopolski',
	'Dynów',
	'Boguchwała',
	'Nowa Sarzyna',
	'Jedlicze',
	'Lesko',
	'Radymno',
	'Zagórz',
	'Pilzno',
	'Sokołów Małopolski',
	'Rymanów',
	'Tyczyn',
	'Pruchnik',
	'Radomyśl Wielki',
	'Kańczuga',
	'Zaklików',
	'Oleszyce',
	'Brzostek',
	'Błażowa',
	'Sieniawa',
	'Dukla',
	'Narol',
	'Cieszanów',
	'Iwonicz-Zdrój',
	'Przecław',
	'Baranów Sandomierski',
	'Ulanów',
	'Kołaczyce',
	'Dubiecko',
	'Białystok',
	'Suwałki',
	'Łomża',
	'Augustów',
	'Bielsk Podlaski',
	'Zambrów',
	'Grajewo',
	'Hajnówka',
	'Sokółka',
	'Łapy',
	'Siemiatycze',
	'Wasilków',
	'Kolno',
	'Mońki',
	'Wysokie Mazowieckie',
	'Czarna Białostocka',
	'Choroszcz',
	'Dąbrowa Białostocka',
	'Sejny',
	'Ciechanowiec',
	'Supraśl',
	'Brańsk',
	'Szczuczyn',
	'Michałowo',
	'Knyszyn',
	'Czyżew',
	'Zabłudów',
	'Krynki',
	'Lipsk',
	'Stawiski',
	'Suchowola',
	'Szepietowo',
	'Nowogród',
	'Drohiczyn',
	'Tykocin',
	'Goniądz',
	'Jedwabne',
	'Rajgród',
	'Kleszczele',
	'Suraż',
	'Gdańsk',
	'Gdynia',
	'Słupsk',
	'Tczew',
	'Wejherowo',
	'Rumia',
	'Starogard Gdański',
	'Chojnice',
	'Malbork',
	'Kwidzyn',
	'Sopot',
	'Lębork',
	'Pruszcz Gdański',
	'Reda',
	'Kościerzyna',
	'Bytów',
	'Ustka',
	'Kartuzy',
	'Człuchów',
	'Puck',
	'Miastko',
	'Sztum',
	'Władysławowo',
	'Nowy Dwór Gdański',
	'Czersk',
	'Prabuty',
	'Pelplin',
	'Skarszewy',
	'Gniew',
	'Żukowo',
	'Czarne',
	'Dzierzgoń',
	'Brusy',
	'Debrzno',
	'Nowy Staw',
	'Łeba',
	'Skórcz',
	'Kępice',
	'Hel',
	'Czarna Woda',
	'Jastarnia',
	'Krynica Morska',
	'Katowice',
	'Częstochowa',
	'Sosnowiec',
	'Gliwice',
	'Zabrze',
	'Bielsko-Biała',
	'Bytom',
	'Rybnik',
	'Ruda Śląska',
	'Tychy',
	'Dąbrowa Górnicza',
	'Chorzów',
	'Jaworzno',
	'Jastrzębie-Zdrój',
	'Mysłowice',
	'Siemianowice Śląskie',
	'Żory',
	'Tarnowskie Góry',
	'Będzin',
	'Piekary Śląskie',
	'Racibórz',
	'Świętochłowice',
	'Zawiercie',
	'Wodzisław Śląski',
	'Mikołów',
	'Knurów',
	'Czechowice-Dziedzice',
	'Cieszyn',
	'Myszków',
	'Czeladź',
	'Żywiec',
	'Czerwionka-Leszczyny',
	'Pszczyna',
	'Lubliniec',
	'Łaziska Górne',
	'Rydułtowy',
	'Orzesze',
	'Bieruń',
	'Pyskowice',
	'Radlin',
	'Lędziny',
	'Radzionków',
	'Ustroń',
	'Skoczów',
	'Pszów',
	'Kłobuck',
	'Wisła',
	'Blachownia',
	'Imielin',
	'Wojkowice',
	'Kalety',
	'Poręba',
	'Miasteczko Śląskie',
	'Sławków',
	'Łazy',
	'Koniecpol',
	'Szczyrk',
	'Siewierz',
	'Kuźnia Raciborska',
	'Żarki',
	'Krzepice',
	'Woźniki',
	'Ogrodzieniec',
	'Strumień',
	'Szczekociny',
	'Toszek',
	'Wilamowice',
	'Koziegłowy',
	'Krzanowice',
	'Pilica',
	'Sośnicowice',
	'Olsztyn',
	'Kielce',
	'Ostrowiec Świętokrzyski',
	'Starachowice',
	'Skarżysko-Kamienna',
	'Sandomierz',
	'Końskie',
	'Busko-Zdrój',
	'Jędrzejów',
	'Staszów',
	'Pińczów',
	'Włoszczowa',
	'Suchedniów',
	'Połaniec',
	'Opatów',
	'Sędziszów',
	'Stąporków',
	'Kazimierza Wielka',
	'Ożarów',
	'Chęciny',
	'Małogoszcz',
	'Chmielnik',
	'Radoszyce',
	'Ćmielów',
	'Kunów',
	'Daleszyce',
	'Wąchock',
	'Koprzywnica',
	'Bodzentyn',
	'Osiek',
	'Zawichost',
	'Morawica',
	'Łagów',
	'Stopnica',
	'Skalbmierz',
	'Działoszyce',
	'Wiślica',
	'Nowy Korczyn',
	'Pacanów',
	'Wodzisław',
	'Opatowiec',
	'Nowa Słupia',
	'Pierzchnica',
	'Iwaniska',
	'Klimontów',
	'Oleśnica',
	'Szydłów',
	'Olsztyn',
	'Elbląg',
	'Ełk',
	'Iława',
	'Ostróda',
	'Giżycko',
	'Kętrzyn',
	'Bartoszyce',
	'Szczytno',
	'Mrągowo',
	'Działdowo',
	'Pisz',
	'Braniewo',
	'Olecko',
	'Lidzbark Warmiński',
	'Morąg',
	'Nidzica',
	'Gołdap',
	'Pasłęk',
	'Węgorzewo',
	'Nowe Miasto Lubawskie',
	'Biskupiec',
	'Lubawa',
	'Dobre Miasto',
	'Orneta',
	'Lidzbark',
	'Olsztynek',
	'Barczewo',
	'Orzysz',
	'Susz',
	'Reszel',
	'Ruciane-Nida',
	'Korsze',
	'Biała Piska',
	'Górowo Iławeckie',
	'Mikołajki',
	'Jeziorany',
	'Ryn',
	'Pieniężno',
	'Tolkmicko',
	'Miłakowo',
	'Pasym',
	'Miłomłyn',
	'Bisztynek',
	'Frombork',
	'Zalewo',
	'Kisielice',
	'Sępopol',
	'Młynary',
	'Wielbark',
	'Poznań',
	'Kalisz',
	'Konin',
	'Piła',
	'Ostrów Wielkopolski',
	'Gniezno',
	'Leszno',
	'Luboń',
	'Września',
	'Swarzędz',
	'Śrem',
	'Krotoszyn',
	'Turek',
	'Jarocin',
	'Wągrowiec',
	'Kościan',
	'Środa Wielkopolska',
	'Koło',
	'Rawicz',
	'Gostyń',
	'Szamotuły',
	'Chodzież',
	'Złotów',
	'Oborniki',
	'Pleszew',
	'Trzcianka',
	'Grodzisk Wielkopolski',
	'Nowy Tomyśl',
	'Ostrzeszów',
	'Kępno',
	'Mosina',
	'Słupca',
	'Wolsztyn',
	'Wronki',
	'Rogoźno',
	'Czarnków',
	'Międzychód',
	'Murowana Goślina',
	'Puszczykowo',
	'Kostrzyn',
	'Opalenica',
	'Pobiedziska',
	'Jastrowie',
	'Pniewy',
	'Witkowo',
	'Kórnik',
	'Trzemeszno',
	'Zbąszyń',
	'Koźmin Wielkopolski',
	'Kłodawa',
	'Krzyż Wielkopolski',
	'Buk',
	'Sieraków',
	'Stęszew',
	'Wieleń',
	'Śmigiel',
	'Czempiń',
	'Wyrzysk',
	'Odolanów',
	'Nowe Skalmierzyce',
	'Zduny',
	'Golina',
	'Skoki',
	'Krobia',
	'Szamocin',
	'Kleczew',
	'Okonek',
	'Nekla',
	'Ujście',
	'Opatówek',
	'Krajenka',
	'Rakoniewice',
	'Miłosław',
	'Sompolno',
	'Gołańcz',
	'Tuliszków',
	'Kobylin',
	'Miejska Górka',
	'Ślesin',
	'Pyzdry',
	'Dobrzyca',
	'Margonin',
	'Zagórów',
	'Lwówek',
	'Łobżenica',
	'Bojanowo',
	'Sulmierzyce',
	'Rydzyna',
	'Poniec',
	'Książ Wielkopolski',
	'Czerniejewo',
	'Wysoka',
	'Kłecko',
	'Borek Wielkopolski',
	'Rychwał',
	'Obrzycko',
	'Osieczna',
	'Żerków',
	'Pogorzela',
	'Raszków',
	'Dąbie',
	'Jutrosin',
	'Grabów nad Prosną',
	'Ostroróg',
	'Mikstat',
	'Chocz',
	'Wielichowo',
	'Krzywiń',
	'Przedecz',
	'Dolsk',
	'Stawiszyn',
	'Jaraczewo',
	'Dobra',
	'Budzyń',
	'Koźminek',
	'Kaczory',
	'Szczecin',
	'Koszalin',
	'Stargard',
	'Kołobrzeg',
	'Świnoujście',
	'Szczecinek',
	'Police',
	'Wałcz',
	'Białogard',
	'Goleniów',
	'Gryfino',
	'Nowogard',
	'Gryfice',
	'Świdwin',
	'Choszczno',
	'Dębno',
	'Barlinek',
	'Darłowo',
	'Złocieniec',
	'Pyrzyce',
	'Sławno',
	'Drawsko Pomorskie',
	'Myślibórz',
	'Łobez',
	'Trzebiatów',
	'Kamień Pomorski',
	'Połczyn-Zdrój',
	'Chojna',
	'Czaplinek',
	'Sianów',
	'Karlino',
	'Międzyzdroje',
	'Borne Sulinowo',
	'Wolin',
	'Kalisz Pomorski',
	'Resko',
	'Bobolice',
	'Płoty',
	'Lipiany',
	'Barwice',
	'Mieszkowice',
	'Maszewo',
	'Chociwel',
	'Mirosławiec',
	'Mielno',
	'Polanów',
	'Recz',
	'Węgorzyno',
	'Dziwnów',
	'Golczewo',
	'Pełczyce',
	'Tychowo',
	'Stepnica',
	'Gościno',
	'Człopa',
	'Dobra',
	'Drawno',
	'Trzcińsko-Zdrój',
	'Dobrzany',
	'Biały Bór',
	'Ińsko',
	'Tuczno',
	'Moryń',
	'Cedynia',
	'Suchań',
	'Nowe Warpno',
];

export const cityDataList: [string, string, string][] = [
	['Wrocław', 'Wrocław', 'dolnośląskie'],
	['Wałbrzych', 'Wałbrzych', 'dolnośląskie'],
	['Legnica', 'Legnica', 'dolnośląskie'],
	['Jelenia Góra', 'Jelenia Góra', 'dolnośląskie'],
	['Lubin', 'lubiński', 'dolnośląskie'],
	['Głogów', 'głogowski', 'dolnośląskie'],
	['Świdnica', 'świdnicki', 'dolnośląskie'],
	['Bolesławiec', 'bolesławiecki', 'dolnośląskie'],
	['Oleśnica', 'oleśnicki', 'dolnośląskie'],
	['Dzierżoniów', 'dzierżoniowski', 'dolnośląskie'],
	['Oława', 'oławski', 'dolnośląskie'],
	['Zgorzelec', 'zgorzelecki', 'dolnośląskie'],
	['Bielawa', 'dzierżoniowski', 'dolnośląskie'],
	['Kłodzko', 'kłodzki', 'dolnośląskie'],
	['Jawor', 'jaworski', 'dolnośląskie'],
	['Świebodzice', 'świdnicki', 'dolnośląskie'],
	['Polkowice', 'polkowicki', 'dolnośląskie'],
	['Nowa Ruda', 'kłodzki', 'dolnośląskie'],
	['Lubań', 'lubański', 'dolnośląskie'],
	['Kamienna Góra', 'kamiennogórski', 'dolnośląskie'],
	['Bogatynia', 'zgorzelecki', 'dolnośląskie'],
	['Strzegom', 'świdnicki', 'dolnośląskie'],
	['Jelcz-Laskowice', 'oławski', 'dolnośląskie'],
	['Złotoryja', 'złotoryjski', 'dolnośląskie'],
	['Boguszów-Gorce', 'wałbrzyski', 'dolnośląskie'],
	['Ząbkowice Śląskie', 'ząbkowicki', 'dolnośląskie'],
	['Chojnów', 'legnicki', 'dolnośląskie'],
	['Trzebnica', 'trzebnicki', 'dolnośląskie'],
	['Brzeg Dolny', 'wołowski', 'dolnośląskie'],
	['Strzelin', 'strzeliński', 'dolnośląskie'],
	['Wołów', 'wołowski', 'dolnośląskie'],
	['Góra', 'górowski', 'dolnośląskie'],
	['Milicz', 'milicki', 'dolnośląskie'],
	['Kowary', 'jeleniogórski', 'dolnośląskie'],
	['Syców', 'oleśnicki', 'dolnośląskie'],
	['Bystrzyca Kłodzka', 'kłodzki', 'dolnośląskie'],
	['Kudowa-Zdrój', 'kłodzki', 'dolnośląskie'],
	['Środa Śląska', 'średzki', 'dolnośląskie'],
	['Oborniki Śląskie', 'trzebnicki', 'dolnośląskie'],
	['Lwówek Śląski', 'lwówecki', 'dolnośląskie'],
	['Ziębice', 'ząbkowicki', 'dolnośląskie'],
	['Chocianów', 'polkowicki', 'dolnośląskie'],
	['Siechnice', 'wrocławski', 'dolnośląskie'],
	['Pieszyce', 'dzierżoniowski', 'dolnośląskie'],
	['Sobótka', 'wrocławski', 'dolnośląskie'],
	['Kąty Wrocławskie', 'wrocławski', 'dolnośląskie'],
	['Żarów', 'świdnicki', 'dolnośląskie'],
	['Twardogóra', 'oleśnicki', 'dolnośląskie'],
	['Gryfów Śląski', 'lwówecki', 'dolnośląskie'],
	['Szklarska Poręba', 'jeleniogórski', 'dolnośląskie'],
	['Piława Górna', 'dzierżoniowski', 'dolnośląskie'],
	['Żmigród', 'trzebnicki', 'dolnośląskie'],
	['Głuszyca', 'wałbrzyski', 'dolnośląskie'],
	['Polanica-Zdrój', 'kłodzki', 'dolnośląskie'],
	['Piechowice', 'jeleniogórski', 'dolnośląskie'],
	['Przemków', 'polkowicki', 'dolnośląskie'],
	['Lubawka', 'kamiennogórski', 'dolnośląskie'],
	['Pieńsk', 'zgorzelecki', 'dolnośląskie'],
	['Stronie Śląskie', 'kłodzki', 'dolnośląskie'],
	['Lądek-Zdrój', 'kłodzki', 'dolnośląskie'],
	['Szczawno-Zdrój', 'wałbrzyski', 'dolnośląskie'],
	['Ścinawa', 'lubiński', 'dolnośląskie'],
	['Szczytna', 'kłodzki', 'dolnośląskie'],
	['Jaworzyna Śląska', 'świdnicki', 'dolnośląskie'],
	['Bolków', 'jaworski', 'dolnośląskie'],
	['Bierutów', 'oleśnicki', 'dolnośląskie'],
	['Jedlina-Zdrój', 'wałbrzyski', 'dolnośląskie'],
	['Karpacz', 'jeleniogórski', 'dolnośląskie'],
	['Duszniki-Zdrój', 'kłodzki', 'dolnośląskie'],
	['Leśna', 'lubański', 'dolnośląskie'],
	['Olszyna', 'lubański', 'dolnośląskie'],
	['Nowogrodziec', 'bolesławiecki', 'dolnośląskie'],
	['Zawidów', 'zgorzelecki', 'dolnośląskie'],
	['Świeradów-Zdrój', 'lubański', 'dolnośląskie'],
	['Mieroszów', 'wałbrzyski', 'dolnośląskie'],
	['Mirsk', 'lwówecki', 'dolnośląskie'],
	['Wojcieszów', 'złotoryjski', 'dolnośląskie'],
	['Prochowice', 'legnicki', 'dolnośląskie'],
	['Niemcza', 'dzierżoniowski', 'dolnośląskie'],
	['Węgliniec', 'zgorzelecki', 'dolnośląskie'],
	['Złoty Stok', 'ząbkowicki', 'dolnośląskie'],
	['Wąsosz', 'górowski', 'dolnośląskie'],
	['Międzylesie', 'kłodzki', 'dolnośląskie'],
	['Bardo', 'ząbkowicki', 'dolnośląskie'],
	['Radków', 'kłodzki', 'dolnośląskie'],
	['Międzybórz', 'oleśnicki', 'dolnośląskie'],
	['Świerzawa', 'złotoryjski', 'dolnośląskie'],
	['Wiązów', 'strzeliński', 'dolnośląskie'],
	['Prusice', 'trzebnicki', 'dolnośląskie'],
	['Lubomierz', 'lwówecki', 'dolnośląskie'],
	['Wleń', 'lwówecki', 'dolnośląskie'],
	['Kamieniec Ząbkowicki', 'ząbkowicki', 'dolnośląskie'],
	['Bydgoszcz', 'Bydgoszcz', 'kujawsko-pomorskie'],
	['Toruń', 'Toruń', 'kujawsko-pomorskie'],
	['Włocławek', 'Włocławek', 'kujawsko-pomorskie'],
	['Grudziądz', 'Grudziądz', 'kujawsko-pomorskie'],
	['Inowrocław', 'inowrocławski', 'kujawsko-pomorskie'],
	['Brodnica', 'brodnicki', 'kujawsko-pomorskie'],
	['Świecie', 'świecki', 'kujawsko-pomorskie'],
	['Chełmno', 'chełmiński', 'kujawsko-pomorskie'],
	['Nakło nad Notecią', 'nakielski', 'kujawsko-pomorskie'],
	['Rypin', 'rypiński', 'kujawsko-pomorskie'],
	['Solec Kujawski', 'bydgoski', 'kujawsko-pomorskie'],
	['Chełmża', 'toruński', 'kujawsko-pomorskie'],
	['Lipno', 'lipnowski', 'kujawsko-pomorskie'],
	['Żnin', 'żniński', 'kujawsko-pomorskie'],
	['Tuchola', 'tucholski', 'kujawsko-pomorskie'],
	['Wąbrzeźno', 'wąbrzeski', 'kujawsko-pomorskie'],
	['Golub-Dobrzyń', 'golubsko-dobrzyński', 'kujawsko-pomorskie'],
	['Aleksandrów Kujawski', 'aleksandrowski', 'kujawsko-pomorskie'],
	['Mogilno', 'mogileński', 'kujawsko-pomorskie'],
	['Koronowo', 'bydgoski', 'kujawsko-pomorskie'],
	['Ciechocinek', 'aleksandrowski', 'kujawsko-pomorskie'],
	['Szubin', 'nakielski', 'kujawsko-pomorskie'],
	['Sępólno Krajeńskie', 'sępoleński', 'kujawsko-pomorskie'],
	['Kruszwica', 'inowrocławski', 'kujawsko-pomorskie'],
	['Janikowo', 'inowrocławski', 'kujawsko-pomorskie'],
	['Barcin', 'żniński', 'kujawsko-pomorskie'],
	['Gniewkowo', 'inowrocławski', 'kujawsko-pomorskie'],
	['Więcbork', 'sępoleński', 'kujawsko-pomorskie'],
	['Nowe', 'świecki', 'kujawsko-pomorskie'],
	['Pakość', 'inowrocławski', 'kujawsko-pomorskie'],
	['Strzelno', 'mogileński', 'kujawsko-pomorskie'],
	['Radziejów', 'radziejowski', 'kujawsko-pomorskie'],
	['Kcynia', 'nakielski', 'kujawsko-pomorskie'],
	['Brześć Kujawski', 'włocławski', 'kujawsko-pomorskie'],
	['Łabiszyn', 'żniński', 'kujawsko-pomorskie'],
	['Piotrków Kujawski', 'radziejowski', 'kujawsko-pomorskie'],
	['Mrocza', 'nakielski', 'kujawsko-pomorskie'],
	['Kowalewo Pomorskie', 'golubsko-dobrzyński', 'kujawsko-pomorskie'],
	['Janowiec Wielkopolski', 'żniński', 'kujawsko-pomorskie'],
	['Jabłonowo Pomorskie', 'brodnicki', 'kujawsko-pomorskie'],
	['Skępe', 'lipnowski', 'kujawsko-pomorskie'],
	['Kowal', 'włocławski', 'kujawsko-pomorskie'],
	['Łasin', 'grudziądzki', 'kujawsko-pomorskie'],
	['Lubraniec', 'włocławski', 'kujawsko-pomorskie'],
	['Izbica Kujawska', 'włocławski', 'kujawsko-pomorskie'],
	['Kamień Krajeński', 'sępoleński', 'kujawsko-pomorskie'],
	['Dobrzyń nad Wisłą', 'lipnowski', 'kujawsko-pomorskie'],
	['Chodecz', 'włocławski', 'kujawsko-pomorskie'],
	['Nieszawa', 'aleksandrowski', 'kujawsko-pomorskie'],
	['Radzyń Chełmiński', 'grudziądzki', 'kujawsko-pomorskie'],
	['Lubień Kujawski', 'włocławski', 'kujawsko-pomorskie'],
	['Górzno', 'brodnicki', 'kujawsko-pomorskie'],
	['Pruszcz', 'świecki', 'kujawsko-pomorskie'],
	['Lublin', 'Lublin', 'lubelskie'],
	['Zamość', 'Zamość', 'lubelskie'],
	['Chełm', 'Chełm', 'lubelskie'],
	['Biała Podlaska', 'Biała Podlaska', 'lubelskie'],
	['Puławy', 'puławski', 'lubelskie'],
	['Świdnik', 'świdnicki', 'lubelskie'],
	['Kraśnik', 'kraśnicki', 'lubelskie'],
	['Łuków', 'łukowski', 'lubelskie'],
	['Biłgoraj', 'biłgorajski', 'lubelskie'],
	['Lubartów', 'lubartowski', 'lubelskie'],
	['Tomaszów Lubelski', 'tomaszowski', 'lubelskie'],
	['Łęczna', 'łęczyński', 'lubelskie'],
	['Krasnystaw', 'krasnostawski', 'lubelskie'],
	['Hrubieszów', 'hrubieszowski', 'lubelskie'],
	['Międzyrzec Podlaski', 'bialski', 'lubelskie'],
	['Dęblin', 'rycki', 'lubelskie'],
	['Radzyń Podlaski', 'radzyński', 'lubelskie'],
	['Włodawa', 'włodawski', 'lubelskie'],
	['Janów Lubelski', 'janowski', 'lubelskie'],
	['Parczew', 'parczewski', 'lubelskie'],
	['Ryki', 'rycki', 'lubelskie'],
	['Poniatowa', 'opolski', 'lubelskie'],
	['Opole Lubelskie', 'opolski', 'lubelskie'],
	['Bełżyce', 'lubelski', 'lubelskie'],
	['Terespol', 'bialski', 'lubelskie'],
	['Szczebrzeszyn', 'zamojski', 'lubelskie'],
	['Bychawa', 'lubelski', 'lubelskie'],
	['Rejowiec Fabryczny', 'chełmski', 'lubelskie'],
	['Nałęczów', 'puławski', 'lubelskie'],
	['Tarnogród', 'biłgorajski', 'lubelskie'],
	['Kock', 'lubartowski', 'lubelskie'],
	['Zwierzyniec', 'zamojski', 'lubelskie'],
	['Krasnobród', 'zamojski', 'lubelskie'],
	['Kazimierz Dolny', 'puławski', 'lubelskie'],
	['Piaski', 'świdnicki', 'lubelskie'],
	['Stoczek Łukowski', 'łukowski', 'lubelskie'],
	['Annopol', 'kraśnicki', 'lubelskie'],
	['Józefów', 'biłgorajski', 'lubelskie'],
	['Lubycza Królewska', 'tomaszowski', 'lubelskie'],
	['Łaszczów', 'tomaszowski', 'lubelskie'],
	['Tyszowce', 'tomaszowski', 'lubelskie'],
	['Ostrów Lubelski', 'lubartowski', 'lubelskie'],
	['Rejowiec', 'chełmski', 'lubelskie'],
	['Urzędów', 'kraśnicki', 'lubelskie'],
	['Modliborzyce', 'janowski', 'lubelskie'],
	['Frampol', 'biłgorajski', 'lubelskie'],
	['Siedliszcze', 'chełmski', 'lubelskie'],
	['Józefów nad Wisłą', 'opolski', 'lubelskie'],
	['Goraj', 'biłgorajski', 'lubelskie'],
	['Izbica', 'krasnostawski', 'lubelskie'],
	['Kamionka', 'lubartowski', 'lubelskie'],
	['Zielona Góra', 'Zielona Góra', 'lubuskie'],
	['Gorzów Wielkopolski', 'Gorzów Wielkopolski', 'lubuskie'],
	['Nowa Sól', 'nowosolski', 'lubuskie'],
	['Żary', 'żarski', 'lubuskie'],
	['Żagań', 'żagański', 'lubuskie'],
	['Świebodzin', 'świebodziński', 'lubuskie'],
	['Międzyrzecz', 'międzyrzecki', 'lubuskie'],
	['Kostrzyn nad Odrą', 'gorzowski', 'lubuskie'],
	['Sulechów', 'zielonogórski', 'lubuskie'],
	['Słubice', 'słubicki', 'lubuskie'],
	['Gubin', 'krośnieński', 'lubuskie'],
	['Lubsko', 'żarski', 'lubuskie'],
	['Wschowa', 'wschowski', 'lubuskie'],
	['Szprotawa', 'żagański', 'lubuskie'],
	['Krosno Odrzańskie', 'krośnieński', 'lubuskie'],
	['Drezdenko', 'strzelecko-drezdenecki', 'lubuskie'],
	['Sulęcin', 'sulęciński', 'lubuskie'],
	['Strzelce Krajeńskie', 'strzelecko-drezdenecki', 'lubuskie'],
	['Skwierzyna', 'międzyrzecki', 'lubuskie'],
	['Kożuchów', 'nowosolski', 'lubuskie'],
	['Witnica', 'gorzowski', 'lubuskie'],
	['Rzepin', 'słubicki', 'lubuskie'],
	['Nowogród Bobrzański', 'zielonogórski', 'lubuskie'],
	['Zbąszynek', 'świebodziński', 'lubuskie'],
	['Bytom Odrzański', 'nowosolski', 'lubuskie'],
	['Jasień', 'żarski', 'lubuskie'],
	['Sława', 'wschowski', 'lubuskie'],
	['Czerwieńsk', 'zielonogórski', 'lubuskie'],
	['Ośno Lubuskie', 'słubicki', 'lubuskie'],
	['Babimost', 'zielonogórski', 'lubuskie'],
	['Iłowa', 'żagański', 'lubuskie'],
	['Kargowa', 'zielonogórski', 'lubuskie'],
	['Małomice', 'żagański', 'lubuskie'],
	['Dobiegniew', 'strzelecko-drezdenecki', 'lubuskie'],
	['Gozdnica', 'żagański', 'lubuskie'],
	['Nowe Miasteczko', 'nowosolski', 'lubuskie'],
	['Cybinka', 'słubicki', 'lubuskie'],
	['Torzym', 'sulęciński', 'lubuskie'],
	['Łęknica', 'żarski', 'lubuskie'],
	['Trzciel', 'międzyrzecki', 'lubuskie'],
	['Lubniewice', 'sulęciński', 'lubuskie'],
	['Otyń', 'nowosolski', 'lubuskie'],
	['Szlichtyngowa', 'wschowski', 'lubuskie'],
	['Łódź', 'Łódź', 'łódzkie'],
	['Piotrków Trybunalski', 'Piotrków Trybunalski', 'łódzkie'],
	['Pabianice', 'pabianicki', 'łódzkie'],
	['Tomaszów Mazowiecki', 'tomaszowski', 'łódzkie'],
	['Bełchatów', 'bełchatowski', 'łódzkie'],
	['Zgierz', 'zgierski', 'łódzkie'],
	['Skierniewice', 'Skierniewice', 'łódzkie'],
	['Radomsko', 'radomszczański', 'łódzkie'],
	['Kutno', 'kutnowski', 'łódzkie'],
	['Sieradz', 'sieradzki', 'łódzkie'],
	['Zduńska Wola', 'zduńskowolski', 'łódzkie'],
	['Łowicz', 'łowicki', 'łódzkie'],
	['Wieluń', 'wieluński', 'łódzkie'],
	['Aleksandrów Łódzki', 'zgierski', 'łódzkie'],
	['Opoczno', 'opoczyński', 'łódzkie'],
	['Ozorków', 'zgierski', 'łódzkie'],
	['Konstantynów Łódzki', 'pabianicki', 'łódzkie'],
	['Rawa Mazowiecka', 'rawski', 'łódzkie'],
	['Łask', 'łaski', 'łódzkie'],
	['Głowno', 'zgierski', 'łódzkie'],
	['Łęczyca', 'łęczycki', 'łódzkie'],
	['Koluszki', 'łódzki wschodni', 'łódzkie'],
	['Brzeziny', 'brzeziński', 'łódzkie'],
	['Wieruszów', 'wieruszowski', 'łódzkie'],
	['Żychlin', 'kutnowski', 'łódzkie'],
	['Zelów', 'bełchatowski', 'łódzkie'],
	['Poddębice', 'poddębicki', 'łódzkie'],
	['Tuszyn', 'łódzki wschodni', 'łódzkie'],
	['Pajęczno', 'pajęczański', 'łódzkie'],
	['Sulejów', 'piotrkowski', 'łódzkie'],
	['Działoszyn', 'pajęczański', 'łódzkie'],
	['Krośniewice', 'kutnowski', 'łódzkie'],
	['Drzewica', 'opoczyński', 'łódzkie'],
	['Przedbórz', 'radomszczański', 'łódzkie'],
	['Stryków', 'zgierski', 'łódzkie'],
	['Rzgów', 'łódzki wschodni', 'łódzkie'],
	['Złoczew', 'sieradzki', 'łódzkie'],
	['Warta', 'sieradzki', 'łódzkie'],
	['Biała Rawska', 'rawski', 'łódzkie'],
	['Uniejów', 'poddębicki', 'łódzkie'],
	['Kamieńsk', 'radomszczański', 'łódzkie'],
	['Wolbórz', 'piotrkowski', 'łódzkie'],
	['Błaszki', 'sieradzki', 'łódzkie'],
	['Szadek', 'zduńskowolski', 'łódzkie'],
	['Piątek', 'łęczycki', 'łódzkie'],
	['Lutomiersk', 'pabianicki', 'łódzkie'],
	['Bolimów', 'skierniewicki', 'łódzkie'],
	['Lututów', 'wieruszowski', 'łódzkie'],
	['Kraków', 'Kraków', 'małopolskie'],
	['Tarnów', 'Tarnów', 'małopolskie'],
	['Nowy Sącz', 'Nowy Sącz', 'małopolskie'],
	['Oświęcim', 'oświęcimski', 'małopolskie'],
	['Chrzanów', 'chrzanowski', 'małopolskie'],
	['Olkusz', 'olkuski', 'małopolskie'],
	['Nowy Targ', 'nowotarski', 'małopolskie'],
	['Bochnia', 'bocheński', 'małopolskie'],
	['Gorlice', 'gorlicki', 'małopolskie'],
	['Zakopane', 'tatrzański', 'małopolskie'],
	['Skawina', 'krakowski', 'małopolskie'],
	['Wieliczka', 'wielicki', 'małopolskie'],
	['Andrychów', 'wadowicki', 'małopolskie'],
	['Trzebinia', 'chrzanowski', 'małopolskie'],
	['Wadowice', 'wadowicki', 'małopolskie'],
	['Kęty', 'oświęcimski', 'małopolskie'],
	['Myślenice', 'myślenicki', 'małopolskie'],
	['Libiąż', 'chrzanowski', 'małopolskie'],
	['Brzesko', 'brzeski', 'małopolskie'],
	['Limanowa', 'limanowski', 'małopolskie'],
	['Niepołomice', 'wielicki', 'małopolskie'],
	['Rabka-Zdrój', 'nowotarski', 'małopolskie'],
	['Dąbrowa Tarnowska', 'dąbrowski', 'małopolskie'],
	['Miechów', 'miechowski', 'małopolskie'],
	['Brzeszcze', 'oświęcimski', 'małopolskie'],
	['Krynica-Zdrój', 'nowosądecki', 'małopolskie'],
	['Bukowno', 'olkuski', 'małopolskie'],
	['Krzeszowice', 'krakowski', 'małopolskie'],
	['Sucha Beskidzka', 'suski', 'małopolskie'],
	['Chełmek', 'oświęcimski', 'małopolskie'],
	['Stary Sącz', 'nowosądecki', 'małopolskie'],
	['Wolbrom', 'olkuski', 'małopolskie'],
	['Mszana Dolna', 'limanowski', 'małopolskie'],
	['Tuchów', 'tarnowski', 'małopolskie'],
	['Sułkowice', 'myślenicki', 'małopolskie'],
	['Dobczyce', 'myślenicki', 'małopolskie'],
	['Grybów', 'nowosądecki', 'małopolskie'],
	['Proszowice', 'proszowicki', 'małopolskie'],
	['Piwniczna-Zdrój', 'nowosądecki', 'małopolskie'],
	['Maków Podhalański', 'suski', 'małopolskie'],
	['Szczawnica', 'nowotarski', 'małopolskie'],
	['Jordanów', 'suski', 'małopolskie'],
	['Muszyna', 'nowosądecki', 'małopolskie'],
	['Biecz', 'gorlicki', 'małopolskie'],
	['Kalwaria Zebrzydowska', 'wadowicki', 'małopolskie'],
	['Słomniki', 'krakowski', 'małopolskie'],
	['Żabno', 'tarnowski', 'małopolskie'],
	['Szczucin', 'dąbrowski', 'małopolskie'],
	['Skała', 'krakowski', 'małopolskie'],
	['Zator', 'oświęcimski', 'małopolskie'],
	['Alwernia', 'chrzanowski', 'małopolskie'],
	['Wojnicz', 'tarnowski', 'małopolskie'],
	['Bobowa', 'gorlicki', 'małopolskie'],
	['Ryglice', 'tarnowski', 'małopolskie'],
	['Radłów', 'tarnowski', 'małopolskie'],
	['Nowy Wiśnicz', 'bocheński', 'małopolskie'],
	['Ciężkowice', 'tarnowski', 'małopolskie'],
	['Świątniki Górne', 'krakowski', 'małopolskie'],
	['Czchów', 'brzeski', 'małopolskie'],
	['Nowe Brzesko', 'proszowicki', 'małopolskie'],
	['Zakliczyn', 'tarnowski', 'małopolskie'],
	['Koszyce', 'proszowicki', 'małopolskie'],
	['Warszawa', 'Warszawa', 'mazowieckie'],
	['Radom', 'Radom', 'mazowieckie'],
	['Płock', 'Płock', 'mazowieckie'],
	['Siedlce', 'Siedlce', 'mazowieckie'],
	['Pruszków', 'pruszkowski', 'mazowieckie'],
	['Legionowo', 'legionowski', 'mazowieckie'],
	['Ostrołęka', 'Ostrołęka', 'mazowieckie'],
	['Piaseczno', 'piaseczyński', 'mazowieckie'],
	['Otwock', 'otwocki', 'mazowieckie'],
	['Ciechanów', 'ciechanowski', 'mazowieckie'],
	['Mińsk Mazowiecki', 'miński', 'mazowieckie'],
	['Żyrardów', 'żyrardowski', 'mazowieckie'],
	['Wołomin', 'wołomiński', 'mazowieckie'],
	['Ząbki', 'wołomiński', 'mazowieckie'],
	['Sochaczew', 'sochaczewski', 'mazowieckie'],
	['Marki', 'wołomiński', 'mazowieckie'],
	['Grodzisk Mazowiecki', 'grodziski', 'mazowieckie'],
	['Mława', 'mławski', 'mazowieckie'],
	['Nowy Dwór Mazowiecki', 'nowodworski', 'mazowieckie'],
	['Wyszków', 'wyszkowski', 'mazowieckie'],
	['Kobyłka', 'wołomiński', 'mazowieckie'],
	['Piastów', 'pruszkowski', 'mazowieckie'],
	['Ostrów Mazowiecka', 'ostrowski', 'mazowieckie'],
	['Płońsk', 'płoński', 'mazowieckie'],
	['Józefów', 'otwocki', 'mazowieckie'],
	['Sulejówek', 'miński', 'mazowieckie'],
	['Pułtusk', 'pułtuski', 'mazowieckie'],
	['Sokołów Podlaski', 'sokołowski', 'mazowieckie'],
	['Gostynin', 'gostyniński', 'mazowieckie'],
	['Pionki', 'radomski', 'mazowieckie'],
	['Sierpc', 'sierpecki', 'mazowieckie'],
	['Zielonka', 'wołomiński', 'mazowieckie'],
	['Garwolin', 'garwoliński', 'mazowieckie'],
	['Kozienice', 'kozienicki', 'mazowieckie'],
	['Przasnysz', 'przasnyski', 'mazowieckie'],
	['Konstancin-Jeziorna', 'piaseczyński', 'mazowieckie'],
	['Łomianki', 'warszawski zachodni', 'mazowieckie'],
	['Grójec', 'grójecki', 'mazowieckie'],
	['Milanówek', 'grodziski', 'mazowieckie'],
	['Brwinów', 'pruszkowski', 'mazowieckie'],
	['Radzymin', 'wołomiński', 'mazowieckie'],
	['Węgrów', 'węgrowski', 'mazowieckie'],
	['Błonie', 'warszawski zachodni', 'mazowieckie'],
	['Góra Kalwaria', 'piaseczyński', 'mazowieckie'],
	['Warka', 'grójecki', 'mazowieckie'],
	['Szydłowiec', 'szydłowiecki', 'mazowieckie'],
	['Ożarów Mazowiecki', 'warszawski zachodni', 'mazowieckie'],
	['Karczew', 'otwocki', 'mazowieckie'],
	['Maków Mazowiecki', 'makowski', 'mazowieckie'],
	['Żuromin', 'żuromiński', 'mazowieckie'],
	['Tłuszcz', 'wołomiński', 'mazowieckie'],
	['Zwoleń', 'zwoleński', 'mazowieckie'],
	['Nasielsk', 'nowodworski', 'mazowieckie'],
	['Łosice', 'łosicki', 'mazowieckie'],
	['Białobrzegi', 'białobrzeski', 'mazowieckie'],
	['Łochów', 'węgrowski', 'mazowieckie'],
	['Mszczonów', 'żyrardowski', 'mazowieckie'],
	['Przysucha', 'przysuski', 'mazowieckie'],
	['Lipsko', 'lipski', 'mazowieckie'],
	['Łaskarzew', 'garwoliński', 'mazowieckie'],
	['Iłża', 'radomski', 'mazowieckie'],
	['Pilawa', 'garwoliński', 'mazowieckie'],
	['Raciąż', 'płoński', 'mazowieckie'],
	['Serock', 'legionowski', 'mazowieckie'],
	['Skaryszew', 'radomski', 'mazowieckie'],
	['Tarczyn', 'piaseczyński', 'mazowieckie'],
	['Gąbin', 'płocki', 'mazowieckie'],
	['Żelechów', 'garwoliński', 'mazowieckie'],
	['Podkowa Leśna', 'grodziski', 'mazowieckie'],
	['Nowe Miasto nad Pilicą', 'grójecki', 'mazowieckie'],
	['Halinów', 'miński', 'mazowieckie'],
	['Mrozy', 'miński', 'mazowieckie'],
	['Myszyniec', 'ostrołęcki', 'mazowieckie'],
	['Zakroczym', 'nowodworski', 'mazowieckie'],
	['Chorzele', 'przasnyski', 'mazowieckie'],
	['Glinojeck', 'ciechanowski', 'mazowieckie'],
	['Kałuszyn', 'miński', 'mazowieckie'],
	['Drobin', 'płocki', 'mazowieckie'],
	['Różan', 'makowski', 'mazowieckie'],
	['Wyszogród', 'płocki', 'mazowieckie'],
	['Mogielnica', 'grójecki', 'mazowieckie'],
	['Kosów Lacki', 'sokołowski', 'mazowieckie'],
	['Sanniki', 'gostyniński', 'mazowieckie'],
	['Brok', 'ostrowski', 'mazowieckie'],
	['Bieżuń', 'żuromiński', 'mazowieckie'],
	['Mordy', 'siedlecki', 'mazowieckie'],
	['Wyśmierzyce', 'białobrzeski', 'mazowieckie'],
	['Solec nad Wisłą', 'lipski', 'mazowieckie'],
	['Cegłów', 'miński', 'mazowieckie'],
	['Czerwińsk nad Wisłą', 'płoński', 'mazowieckie'],
	['Nowe Miasto', 'płoński', 'mazowieckie'],
	['Sochocin', 'płoński', 'mazowieckie'],
	['Jedlnia-Letnisko', 'radomski', 'mazowieckie'],
	['Lubowidz', 'żuromiński', 'mazowieckie'],
	['Wiskitki', 'żyrardowski', 'mazowieckie'],
	['Opole', 'Opole', 'opolskie'],
	['Kędzierzyn-Koźle', 'kędzierzyńsko-kozielski', 'opolskie'],
	['Nysa', 'nyski', 'opolskie'],
	['Brzeg', 'brzeski', 'opolskie'],
	['Kluczbork', 'kluczborski', 'opolskie'],
	['Prudnik', 'prudnicki', 'opolskie'],
	['Strzelce Opolskie', 'strzelecki', 'opolskie'],
	['Namysłów', 'namysłowski', 'opolskie'],
	['Krapkowice', 'krapkowicki', 'opolskie'],
	['Głuchołazy', 'nyski', 'opolskie'],
	['Głubczyce', 'głubczycki', 'opolskie'],
	['Zdzieszowice', 'krapkowicki', 'opolskie'],
	['Olesno', 'oleski', 'opolskie'],
	['Ozimek', 'opolski', 'opolskie'],
	['Grodków', 'brzeski', 'opolskie'],
	['Praszka', 'oleski', 'opolskie'],
	['Paczków', 'nyski', 'opolskie'],
	['Zawadzkie', 'strzelecki', 'opolskie'],
	['Gogolin', 'krapkowicki', 'opolskie'],
	['Otmuchów', 'nyski', 'opolskie'],
	['Niemodlin', 'opolski', 'opolskie'],
	['Kietrz', 'głubczycki', 'opolskie'],
	['Wołczyn', 'kluczborski', 'opolskie'],
	['Lewin Brzeski', 'brzeski', 'opolskie'],
	['Głogówek', 'prudnicki', 'opolskie'],
	['Tułowice', 'opolski', 'opolskie'],
	['Dobrodzień', 'oleski', 'opolskie'],
	['Byczyna', 'kluczborski', 'opolskie'],
	['Kolonowskie', 'strzelecki', 'opolskie'],
	['Baborów', 'głubczycki', 'opolskie'],
	['Prószków', 'opolski', 'opolskie'],
	['Leśnica', 'strzelecki', 'opolskie'],
	['Gorzów Śląski', 'oleski', 'opolskie'],
	['Biała', 'prudnicki', 'opolskie'],
	['Korfantów', 'nyski', 'opolskie'],
	['Ujazd', 'strzelecki', 'opolskie'],
	['Rzeszów', 'Rzeszów', 'podkarpackie'],
	['Przemyśl', 'Przemyśl', 'podkarpackie'],
	['Stalowa Wola', 'stalowowolski', 'podkarpackie'],
	['Mielec', 'mielecki', 'podkarpackie'],
	['Tarnobrzeg', 'Tarnobrzeg', 'podkarpackie'],
	['Krosno', 'Krosno', 'podkarpackie'],
	['Dębica', 'dębicki', 'podkarpackie'],
	['Jarosław', 'jarosławski', 'podkarpackie'],
	['Sanok', 'sanocki', 'podkarpackie'],
	['Jasło', 'jasielski', 'podkarpackie'],
	['Łańcut', 'łańcucki', 'podkarpackie'],
	['Ropczyce', 'ropczycko-sędziszowski', 'podkarpackie'],
	['Przeworsk', 'przeworski', 'podkarpackie'],
	['Nisko', 'niżański', 'podkarpackie'],
	['Leżajsk', 'leżajski', 'podkarpackie'],
	['Lubaczów', 'lubaczowski', 'podkarpackie'],
	['Nowa Dęba', 'tarnobrzeski', 'podkarpackie'],
	['Kolbuszowa', 'kolbuszowski', 'podkarpackie'],
	['Ustrzyki Dolne', 'bieszczadzki', 'podkarpackie'],
	['Strzyżów', 'strzyżowski', 'podkarpackie'],
	['Sędziszów Małopolski', 'ropczycko-sędziszowski', 'podkarpackie'],
	['Brzozów', 'brzozowski', 'podkarpackie'],
	['Rudnik nad Sanem', 'niżański', 'podkarpackie'],
	['Głogów Małopolski', 'rzeszowski', 'podkarpackie'],
	['Dynów', 'rzeszowski', 'podkarpackie'],
	['Boguchwała', 'rzeszowski', 'podkarpackie'],
	['Nowa Sarzyna', 'leżajski', 'podkarpackie'],
	['Jedlicze', 'krośnieński', 'podkarpackie'],
	['Lesko', 'leski', 'podkarpackie'],
	['Radymno', 'jarosławski', 'podkarpackie'],
	['Zagórz', 'sanocki', 'podkarpackie'],
	['Pilzno', 'dębicki', 'podkarpackie'],
	['Sokołów Małopolski', 'rzeszowski', 'podkarpackie'],
	['Rymanów', 'krośnieński', 'podkarpackie'],
	['Tyczyn', 'rzeszowski', 'podkarpackie'],
	['Pruchnik', 'jarosławski', 'podkarpackie'],
	['Radomyśl Wielki', 'mielecki', 'podkarpackie'],
	['Kańczuga', 'przeworski', 'podkarpackie'],
	['Zaklików', 'stalowowolski', 'podkarpackie'],
	['Oleszyce', 'lubaczowski', 'podkarpackie'],
	['Brzostek', 'dębicki', 'podkarpackie'],
	['Błażowa', 'rzeszowski', 'podkarpackie'],
	['Sieniawa', 'przeworski', 'podkarpackie'],
	['Dukla', 'krośnieński', 'podkarpackie'],
	['Narol', 'lubaczowski', 'podkarpackie'],
	['Cieszanów', 'lubaczowski', 'podkarpackie'],
	['Iwonicz-Zdrój', 'krośnieński', 'podkarpackie'],
	['Przecław', 'mielecki', 'podkarpackie'],
	['Baranów Sandomierski', 'tarnobrzeski', 'podkarpackie'],
	['Ulanów', 'niżański', 'podkarpackie'],
	['Kołaczyce', 'jasielski', 'podkarpackie'],
	['Dubiecko', 'przemyski', 'podkarpackie'],
	['Białystok', 'Białystok', 'podlaskie'],
	['Suwałki', 'Suwałki', 'podlaskie'],
	['Łomża', 'Łomża', 'podlaskie'],
	['Augustów', 'augustowski', 'podlaskie'],
	['Bielsk Podlaski', 'bielski', 'podlaskie'],
	['Zambrów', 'zambrowski', 'podlaskie'],
	['Grajewo', 'grajewski', 'podlaskie'],
	['Hajnówka', 'hajnowski', 'podlaskie'],
	['Sokółka', 'sokólski', 'podlaskie'],
	['Łapy', 'białostocki', 'podlaskie'],
	['Siemiatycze', 'siemiatycki', 'podlaskie'],
	['Wasilków', 'białostocki', 'podlaskie'],
	['Kolno', 'kolneński', 'podlaskie'],
	['Mońki', 'moniecki', 'podlaskie'],
	['Wysokie Mazowieckie', 'wysokomazowiecki', 'podlaskie'],
	['Czarna Białostocka', 'białostocki', 'podlaskie'],
	['Choroszcz', 'białostocki', 'podlaskie'],
	['Dąbrowa Białostocka', 'sokólski', 'podlaskie'],
	['Sejny', 'sejneński', 'podlaskie'],
	['Ciechanowiec', 'wysokomazowiecki', 'podlaskie'],
	['Supraśl', 'białostocki', 'podlaskie'],
	['Brańsk', 'bielski', 'podlaskie'],
	['Szczuczyn', 'grajewski', 'podlaskie'],
	['Michałowo', 'białostocki', 'podlaskie'],
	['Knyszyn', 'moniecki', 'podlaskie'],
	['Czyżew', 'wysokomazowiecki', 'podlaskie'],
	['Zabłudów', 'białostocki', 'podlaskie'],
	['Krynki', 'sokólski', 'podlaskie'],
	['Lipsk', 'augustowski', 'podlaskie'],
	['Stawiski', 'kolneński', 'podlaskie'],
	['Suchowola', 'sokólski', 'podlaskie'],
	['Szepietowo', 'wysokomazowiecki', 'podlaskie'],
	['Nowogród', 'łomżyński', 'podlaskie'],
	['Drohiczyn', 'siemiatycki', 'podlaskie'],
	['Tykocin', 'białostocki', 'podlaskie'],
	['Goniądz', 'moniecki', 'podlaskie'],
	['Jedwabne', 'łomżyński', 'podlaskie'],
	['Rajgród', 'grajewski', 'podlaskie'],
	['Kleszczele', 'hajnowski', 'podlaskie'],
	['Suraż', 'białostocki', 'podlaskie'],
	['Gdańsk', 'Gdańsk', 'pomorskie'],
	['Gdynia', 'Gdynia', 'pomorskie'],
	['Słupsk', 'Słupsk', 'pomorskie'],
	['Tczew', 'tczewski', 'pomorskie'],
	['Wejherowo', 'wejherowski', 'pomorskie'],
	['Rumia', 'wejherowski', 'pomorskie'],
	['Starogard Gdański', 'starogardzki', 'pomorskie'],
	['Chojnice', 'chojnicki', 'pomorskie'],
	['Malbork', 'malborski', 'pomorskie'],
	['Kwidzyn', 'kwidzyński', 'pomorskie'],
	['Sopot', 'Sopot', 'pomorskie'],
	['Lębork', 'lęborski', 'pomorskie'],
	['Pruszcz Gdański', 'gdański', 'pomorskie'],
	['Reda', 'wejherowski', 'pomorskie'],
	['Kościerzyna', 'kościerski', 'pomorskie'],
	['Bytów', 'bytowski', 'pomorskie'],
	['Ustka', 'słupski', 'pomorskie'],
	['Kartuzy', 'kartuski', 'pomorskie'],
	['Człuchów', 'człuchowski', 'pomorskie'],
	['Puck', 'pucki', 'pomorskie'],
	['Miastko', 'bytowski', 'pomorskie'],
	['Sztum', 'sztumski', 'pomorskie'],
	['Władysławowo', 'pucki', 'pomorskie'],
	['Nowy Dwór Gdański', 'nowodworski', 'pomorskie'],
	['Czersk', 'chojnicki', 'pomorskie'],
	['Prabuty', 'kwidzyński', 'pomorskie'],
	['Pelplin', 'tczewski', 'pomorskie'],
	['Skarszewy', 'starogardzki', 'pomorskie'],
	['Gniew', 'tczewski', 'pomorskie'],
	['Żukowo', 'kartuski', 'pomorskie'],
	['Czarne', 'człuchowski', 'pomorskie'],
	['Dzierzgoń', 'sztumski', 'pomorskie'],
	['Brusy', 'chojnicki', 'pomorskie'],
	['Debrzno', 'człuchowski', 'pomorskie'],
	['Nowy Staw', 'malborski', 'pomorskie'],
	['Łeba', 'lęborski', 'pomorskie'],
	['Skórcz', 'starogardzki', 'pomorskie'],
	['Kępice', 'słupski', 'pomorskie'],
	['Hel', 'pucki', 'pomorskie'],
	['Czarna Woda', 'starogardzki', 'pomorskie'],
	['Jastarnia', 'pucki', 'pomorskie'],
	['Krynica Morska', 'nowodworski', 'pomorskie'],
	['Katowice', 'Katowice', 'śląskie'],
	['Częstochowa', 'Częstochowa', 'śląskie'],
	['Sosnowiec', 'Sosnowiec', 'śląskie'],
	['Gliwice', 'Gliwice', 'śląskie'],
	['Zabrze', 'Zabrze', 'śląskie'],
	['Bielsko-Biała', 'Bielsko-Biała', 'śląskie'],
	['Bytom', 'Bytom', 'śląskie'],
	['Rybnik', 'Rybnik', 'śląskie'],
	['Ruda Śląska', 'Ruda Śląska', 'śląskie'],
	['Tychy', 'Tychy', 'śląskie'],
	['Dąbrowa Górnicza', 'Dąbrowa Górnicza', 'śląskie'],
	['Chorzów', 'Chorzów', 'śląskie'],
	['Jaworzno', 'Jaworzno', 'śląskie'],
	['Jastrzębie-Zdrój', 'Jastrzębie-Zdrój', 'śląskie'],
	['Mysłowice', 'Mysłowice', 'śląskie'],
	['Siemianowice Śląskie', 'Siemianowice Śląskie', 'śląskie'],
	['Żory', 'Żory', 'śląskie'],
	['Tarnowskie Góry', 'tarnogórski', 'śląskie'],
	['Będzin', 'będziński', 'śląskie'],
	['Piekary Śląskie', 'Piekary Śląskie', 'śląskie'],
	['Racibórz', 'raciborski', 'śląskie'],
	['Świętochłowice', 'Świętochłowice', 'śląskie'],
	['Zawiercie', 'zawierciański', 'śląskie'],
	['Wodzisław Śląski', 'wodzisławski', 'śląskie'],
	['Mikołów', 'mikołowski', 'śląskie'],
	['Knurów', 'gliwicki', 'śląskie'],
	['Czechowice-Dziedzice', 'bielski', 'śląskie'],
	['Cieszyn', 'cieszyński', 'śląskie'],
	['Myszków', 'myszkowski', 'śląskie'],
	['Czeladź', 'będziński', 'śląskie'],
	['Żywiec', 'żywiecki', 'śląskie'],
	['Czerwionka-Leszczyny', 'rybnicki', 'śląskie'],
	['Pszczyna', 'pszczyński', 'śląskie'],
	['Lubliniec', 'lubliniecki', 'śląskie'],
	['Łaziska Górne', 'mikołowski', 'śląskie'],
	['Rydułtowy', 'wodzisławski', 'śląskie'],
	['Orzesze', 'mikołowski', 'śląskie'],
	['Bieruń', 'bieruńsko-lędziński', 'śląskie'],
	['Pyskowice', 'gliwicki', 'śląskie'],
	['Radlin', 'wodzisławski', 'śląskie'],
	['Lędziny', 'bieruńsko-lędziński', 'śląskie'],
	['Radzionków', 'tarnogórski', 'śląskie'],
	['Ustroń', 'cieszyński', 'śląskie'],
	['Skoczów', 'cieszyński', 'śląskie'],
	['Pszów', 'wodzisławski', 'śląskie'],
	['Kłobuck', 'kłobucki', 'śląskie'],
	['Wisła', 'cieszyński', 'śląskie'],
	['Blachownia', 'częstochowski', 'śląskie'],
	['Imielin', 'bieruńsko-lędziński', 'śląskie'],
	['Wojkowice', 'będziński', 'śląskie'],
	['Kalety', 'tarnogórski', 'śląskie'],
	['Poręba', 'zawierciański', 'śląskie'],
	['Miasteczko Śląskie', 'tarnogórski', 'śląskie'],
	['Sławków', 'będziński', 'śląskie'],
	['Łazy', 'zawierciański', 'śląskie'],
	['Koniecpol', 'częstochowski', 'śląskie'],
	['Szczyrk', 'bielski', 'śląskie'],
	['Siewierz', 'będziński', 'śląskie'],
	['Kuźnia Raciborska', 'raciborski', 'śląskie'],
	['Żarki', 'myszkowski', 'śląskie'],
	['Krzepice', 'kłobucki', 'śląskie'],
	['Woźniki', 'lubliniecki', 'śląskie'],
	['Ogrodzieniec', 'zawierciański', 'śląskie'],
	['Strumień', 'cieszyński', 'śląskie'],
	['Szczekociny', 'zawierciański', 'śląskie'],
	['Toszek', 'gliwicki', 'śląskie'],
	['Wilamowice', 'bielski', 'śląskie'],
	['Koziegłowy', 'myszkowski', 'śląskie'],
	['Krzanowice', 'raciborski', 'śląskie'],
	['Pilica', 'zawierciański', 'śląskie'],
	['Sośnicowice', 'gliwicki', 'śląskie'],
	['Olsztyn', 'częstochowski', 'śląskie'],
	['Kielce', 'Kielce', 'świętokrzyskie'],
	['Ostrowiec Świętokrzyski', 'ostrowiecki', 'świętokrzyskie'],
	['Starachowice', 'starachowicki', 'świętokrzyskie'],
	['Skarżysko-Kamienna', 'skarżyski', 'świętokrzyskie'],
	['Sandomierz', 'sandomierski', 'świętokrzyskie'],
	['Końskie', 'konecki', 'świętokrzyskie'],
	['Busko-Zdrój', 'buski', 'świętokrzyskie'],
	['Jędrzejów', 'jędrzejowski', 'świętokrzyskie'],
	['Staszów', 'staszowski', 'świętokrzyskie'],
	['Pińczów', 'pińczowski', 'świętokrzyskie'],
	['Włoszczowa', 'włoszczowski', 'świętokrzyskie'],
	['Suchedniów', 'skarżyski', 'świętokrzyskie'],
	['Połaniec', 'staszowski', 'świętokrzyskie'],
	['Opatów', 'opatowski', 'świętokrzyskie'],
	['Sędziszów', 'jędrzejowski', 'świętokrzyskie'],
	['Stąporków', 'konecki', 'świętokrzyskie'],
	['Kazimierza Wielka', 'kazimierski', 'świętokrzyskie'],
	['Ożarów', 'opatowski', 'świętokrzyskie'],
	['Chęciny', 'kielecki', 'świętokrzyskie'],
	['Małogoszcz', 'jędrzejowski', 'świętokrzyskie'],
	['Chmielnik', 'kielecki', 'świętokrzyskie'],
	['Radoszyce', 'konecki', 'świętokrzyskie'],
	['Ćmielów', 'ostrowiecki', 'świętokrzyskie'],
	['Kunów', 'ostrowiecki', 'świętokrzyskie'],
	['Daleszyce', 'kielecki', 'świętokrzyskie'],
	['Wąchock', 'starachowicki', 'świętokrzyskie'],
	['Koprzywnica', 'sandomierski', 'świętokrzyskie'],
	['Bodzentyn', 'kielecki', 'świętokrzyskie'],
	['Osiek', 'staszowski', 'świętokrzyskie'],
	['Zawichost', 'sandomierski', 'świętokrzyskie'],
	['Morawica', 'kielecki', 'świętokrzyskie'],
	['Łagów', 'kielecki', 'świętokrzyskie'],
	['Stopnica', 'buski', 'świętokrzyskie'],
	['Skalbmierz', 'kazimierski', 'świętokrzyskie'],
	['Działoszyce', 'pińczowski', 'świętokrzyskie'],
	['Wiślica', 'buski', 'świętokrzyskie'],
	['Nowy Korczyn', 'buski', 'świętokrzyskie'],
	['Pacanów', 'buski', 'świętokrzyskie'],
	['Wodzisław', 'jędrzejowski', 'świętokrzyskie'],
	['Opatowiec', 'kazimierski', 'świętokrzyskie'],
	['Nowa Słupia', 'kielecki', 'świętokrzyskie'],
	['Pierzchnica', 'kielecki', 'świętokrzyskie'],
	['Iwaniska', 'opatowski', 'świętokrzyskie'],
	['Klimontów', 'sandomierski', 'świętokrzyskie'],
	['Oleśnica', 'staszowski', 'świętokrzyskie'],
	['Szydłów', 'staszowski', 'świętokrzyskie'],
	['Olsztyn', 'Olsztyn', 'warmińsko-mazurskie'],
	['Elbląg', 'Elbląg', 'warmińsko-mazurskie'],
	['Ełk', 'ełcki', 'warmińsko-mazurskie'],
	['Iława', 'iławski', 'warmińsko-mazurskie'],
	['Ostróda', 'ostródzki', 'warmińsko-mazurskie'],
	['Giżycko', 'giżycki', 'warmińsko-mazurskie'],
	['Kętrzyn', 'kętrzyński', 'warmińsko-mazurskie'],
	['Bartoszyce', 'bartoszycki', 'warmińsko-mazurskie'],
	['Szczytno', 'szczycieński', 'warmińsko-mazurskie'],
	['Mrągowo', 'mrągowski', 'warmińsko-mazurskie'],
	['Działdowo', 'działdowski', 'warmińsko-mazurskie'],
	['Pisz', 'piski', 'warmińsko-mazurskie'],
	['Braniewo', 'braniewski', 'warmińsko-mazurskie'],
	['Olecko', 'olecki', 'warmińsko-mazurskie'],
	['Lidzbark Warmiński', 'lidzbarski', 'warmińsko-mazurskie'],
	['Morąg', 'ostródzki', 'warmińsko-mazurskie'],
	['Nidzica', 'nidzicki', 'warmińsko-mazurskie'],
	['Gołdap', 'gołdapski', 'warmińsko-mazurskie'],
	['Pasłęk', 'elbląski', 'warmińsko-mazurskie'],
	['Węgorzewo', 'węgorzewski', 'warmińsko-mazurskie'],
	['Nowe Miasto Lubawskie', 'nowomiejski', 'warmińsko-mazurskie'],
	['Biskupiec', 'olsztyński', 'warmińsko-mazurskie'],
	['Lubawa', 'iławski', 'warmińsko-mazurskie'],
	['Dobre Miasto', 'olsztyński', 'warmińsko-mazurskie'],
	['Orneta', 'lidzbarski', 'warmińsko-mazurskie'],
	['Lidzbark', 'działdowski', 'warmińsko-mazurskie'],
	['Olsztynek', 'olsztyński', 'warmińsko-mazurskie'],
	['Barczewo', 'olsztyński', 'warmińsko-mazurskie'],
	['Orzysz', 'piski', 'warmińsko-mazurskie'],
	['Susz', 'iławski', 'warmińsko-mazurskie'],
	['Reszel', 'kętrzyński', 'warmińsko-mazurskie'],
	['Ruciane-Nida', 'piski', 'warmińsko-mazurskie'],
	['Korsze', 'kętrzyński', 'warmińsko-mazurskie'],
	['Biała Piska', 'piski', 'warmińsko-mazurskie'],
	['Górowo Iławeckie', 'bartoszycki', 'warmińsko-mazurskie'],
	['Mikołajki', 'mrągowski', 'warmińsko-mazurskie'],
	['Jeziorany', 'olsztyński', 'warmińsko-mazurskie'],
	['Ryn', 'giżycki', 'warmińsko-mazurskie'],
	['Pieniężno', 'braniewski', 'warmińsko-mazurskie'],
	['Tolkmicko', 'elbląski', 'warmińsko-mazurskie'],
	['Miłakowo', 'ostródzki', 'warmińsko-mazurskie'],
	['Pasym', 'szczycieński', 'warmińsko-mazurskie'],
	['Miłomłyn', 'ostródzki', 'warmińsko-mazurskie'],
	['Bisztynek', 'bartoszycki', 'warmińsko-mazurskie'],
	['Frombork', 'braniewski', 'warmińsko-mazurskie'],
	['Zalewo', 'iławski', 'warmińsko-mazurskie'],
	['Kisielice', 'iławski', 'warmińsko-mazurskie'],
	['Sępopol', 'bartoszycki', 'warmińsko-mazurskie'],
	['Młynary', 'elbląski', 'warmińsko-mazurskie'],
	['Wielbark', 'szczycieński', 'warmińsko-mazurskie'],
	['Poznań', 'Poznań', 'wielkopolskie'],
	['Kalisz', 'Kalisz', 'wielkopolskie'],
	['Konin', 'Konin', 'wielkopolskie'],
	['Piła', 'pilski', 'wielkopolskie'],
	['Ostrów Wielkopolski', 'ostrowski', 'wielkopolskie'],
	['Gniezno', 'gnieźnieński', 'wielkopolskie'],
	['Leszno', 'Leszno', 'wielkopolskie'],
	['Luboń', 'poznański', 'wielkopolskie'],
	['Września', 'wrzesiński', 'wielkopolskie'],
	['Swarzędz', 'poznański', 'wielkopolskie'],
	['Śrem', 'śremski', 'wielkopolskie'],
	['Krotoszyn', 'krotoszyński', 'wielkopolskie'],
	['Turek', 'turecki', 'wielkopolskie'],
	['Jarocin', 'jarociński', 'wielkopolskie'],
	['Wągrowiec', 'wągrowiecki', 'wielkopolskie'],
	['Kościan', 'kościański', 'wielkopolskie'],
	['Środa Wielkopolska', 'średzki', 'wielkopolskie'],
	['Koło', 'kolski', 'wielkopolskie'],
	['Rawicz', 'rawicki', 'wielkopolskie'],
	['Gostyń', 'gostyński', 'wielkopolskie'],
	['Szamotuły', 'szamotulski', 'wielkopolskie'],
	['Chodzież', 'chodzieski', 'wielkopolskie'],
	['Złotów', 'złotowski', 'wielkopolskie'],
	['Oborniki', 'obornicki', 'wielkopolskie'],
	['Pleszew', 'pleszewski', 'wielkopolskie'],
	['Trzcianka', 'czarnkowsko-trzcianecki', 'wielkopolskie'],
	['Grodzisk Wielkopolski', 'grodziski', 'wielkopolskie'],
	['Nowy Tomyśl', 'nowotomyski', 'wielkopolskie'],
	['Ostrzeszów', 'ostrzeszowski', 'wielkopolskie'],
	['Kępno', 'kępiński', 'wielkopolskie'],
	['Mosina', 'poznański', 'wielkopolskie'],
	['Słupca', 'słupecki', 'wielkopolskie'],
	['Wolsztyn', 'wolsztyński', 'wielkopolskie'],
	['Wronki', 'szamotulski', 'wielkopolskie'],
	['Rogoźno', 'obornicki', 'wielkopolskie'],
	['Czarnków', 'czarnkowsko-trzcianecki', 'wielkopolskie'],
	['Międzychód', 'międzychodzki', 'wielkopolskie'],
	['Murowana Goślina', 'poznański', 'wielkopolskie'],
	['Puszczykowo', 'poznański', 'wielkopolskie'],
	['Kostrzyn', 'poznański', 'wielkopolskie'],
	['Opalenica', 'nowotomyski', 'wielkopolskie'],
	['Pobiedziska', 'poznański', 'wielkopolskie'],
	['Jastrowie', 'złotowski', 'wielkopolskie'],
	['Pniewy', 'szamotulski', 'wielkopolskie'],
	['Witkowo', 'gnieźnieński', 'wielkopolskie'],
	['Kórnik', 'poznański', 'wielkopolskie'],
	['Trzemeszno', 'gnieźnieński', 'wielkopolskie'],
	['Zbąszyń', 'nowotomyski', 'wielkopolskie'],
	['Koźmin Wielkopolski', 'krotoszyński', 'wielkopolskie'],
	['Kłodawa', 'kolski', 'wielkopolskie'],
	['Krzyż Wielkopolski', 'czarnkowsko-trzcianecki', 'wielkopolskie'],
	['Buk', 'poznański', 'wielkopolskie'],
	['Sieraków', 'międzychodzki', 'wielkopolskie'],
	['Stęszew', 'poznański', 'wielkopolskie'],
	['Wieleń', 'czarnkowsko-trzcianecki', 'wielkopolskie'],
	['Śmigiel', 'kościański', 'wielkopolskie'],
	['Czempiń', 'kościański', 'wielkopolskie'],
	['Wyrzysk', 'pilski', 'wielkopolskie'],
	['Odolanów', 'ostrowski', 'wielkopolskie'],
	['Nowe Skalmierzyce', 'ostrowski', 'wielkopolskie'],
	['Zduny', 'krotoszyński', 'wielkopolskie'],
	['Golina', 'koniński', 'wielkopolskie'],
	['Skoki', 'wągrowiecki', 'wielkopolskie'],
	['Krobia', 'gostyński', 'wielkopolskie'],
	['Szamocin', 'chodzieski', 'wielkopolskie'],
	['Kleczew', 'koniński', 'wielkopolskie'],
	['Okonek', 'złotowski', 'wielkopolskie'],
	['Nekla', 'wrzesiński', 'wielkopolskie'],
	['Ujście', 'pilski', 'wielkopolskie'],
	['Opatówek', 'kaliski', 'wielkopolskie'],
	['Krajenka', 'złotowski', 'wielkopolskie'],
	['Rakoniewice', 'grodziski', 'wielkopolskie'],
	['Miłosław', 'wrzesiński', 'wielkopolskie'],
	['Sompolno', 'koniński', 'wielkopolskie'],
	['Gołańcz', 'wągrowiecki', 'wielkopolskie'],
	['Tuliszków', 'turecki', 'wielkopolskie'],
	['Kobylin', 'krotoszyński', 'wielkopolskie'],
	['Miejska Górka', 'rawicki', 'wielkopolskie'],
	['Ślesin', 'koniński', 'wielkopolskie'],
	['Pyzdry', 'wrzesiński', 'wielkopolskie'],
	['Dobrzyca', 'pleszewski', 'wielkopolskie'],
	['Margonin', 'chodzieski', 'wielkopolskie'],
	['Zagórów', 'słupecki', 'wielkopolskie'],
	['Lwówek', 'nowotomyski', 'wielkopolskie'],
	['Łobżenica', 'pilski', 'wielkopolskie'],
	['Bojanowo', 'rawicki', 'wielkopolskie'],
	['Sulmierzyce', 'krotoszyński', 'wielkopolskie'],
	['Rydzyna', 'leszczyński', 'wielkopolskie'],
	['Poniec', 'gostyński', 'wielkopolskie'],
	['Książ Wielkopolski', 'śremski', 'wielkopolskie'],
	['Czerniejewo', 'gnieźnieński', 'wielkopolskie'],
	['Wysoka', 'pilski', 'wielkopolskie'],
	['Kłecko', 'gnieźnieński', 'wielkopolskie'],
	['Borek Wielkopolski', 'gostyński', 'wielkopolskie'],
	['Rychwał', 'koniński', 'wielkopolskie'],
	['Obrzycko', 'szamotulski', 'wielkopolskie'],
	['Osieczna', 'leszczyński', 'wielkopolskie'],
	['Żerków', 'jarociński', 'wielkopolskie'],
	['Pogorzela', 'gostyński', 'wielkopolskie'],
	['Raszków', 'ostrowski', 'wielkopolskie'],
	['Dąbie', 'kolski', 'wielkopolskie'],
	['Jutrosin', 'rawicki', 'wielkopolskie'],
	['Grabów nad Prosną', 'ostrzeszowski', 'wielkopolskie'],
	['Ostroróg', 'szamotulski', 'wielkopolskie'],
	['Mikstat', 'ostrzeszowski', 'wielkopolskie'],
	['Chocz', 'pleszewski', 'wielkopolskie'],
	['Wielichowo', 'grodziski', 'wielkopolskie'],
	['Krzywiń', 'kościański', 'wielkopolskie'],
	['Przedecz', 'kolski', 'wielkopolskie'],
	['Dolsk', 'śremski', 'wielkopolskie'],
	['Stawiszyn', 'kaliski', 'wielkopolskie'],
	['Jaraczewo', 'jarociński', 'wielkopolskie'],
	['Dobra', 'turecki', 'wielkopolskie'],
	['Budzyń', 'chodzieski', 'wielkopolskie'],
	['Koźminek', 'kaliski', 'wielkopolskie'],
	['Kaczory', 'pilski', 'wielkopolskie'],
	['Szczecin', 'Szczecin', 'zachodniopomorskie'],
	['Koszalin', 'Koszalin', 'zachodniopomorskie'],
	['Stargard', 'stargardzki', 'zachodniopomorskie'],
	['Kołobrzeg', 'kołobrzeski', 'zachodniopomorskie'],
	['Świnoujście', 'Świnoujście', 'zachodniopomorskie'],
	['Szczecinek', 'szczecinecki', 'zachodniopomorskie'],
	['Police', 'policki', 'zachodniopomorskie'],
	['Wałcz', 'wałecki', 'zachodniopomorskie'],
	['Białogard', 'białogardzki', 'zachodniopomorskie'],
	['Goleniów', 'goleniowski', 'zachodniopomorskie'],
	['Gryfino', 'gryfiński', 'zachodniopomorskie'],
	['Nowogard', 'goleniowski', 'zachodniopomorskie'],
	['Gryfice', 'gryficki', 'zachodniopomorskie'],
	['Świdwin', 'świdwiński', 'zachodniopomorskie'],
	['Choszczno', 'choszczeński', 'zachodniopomorskie'],
	['Dębno', 'myśliborski', 'zachodniopomorskie'],
	['Barlinek', 'myśliborski', 'zachodniopomorskie'],
	['Darłowo', 'sławieński', 'zachodniopomorskie'],
	['Złocieniec', 'drawski', 'zachodniopomorskie'],
	['Pyrzyce', 'pyrzycki', 'zachodniopomorskie'],
	['Sławno', 'sławieński', 'zachodniopomorskie'],
	['Drawsko Pomorskie', 'drawski', 'zachodniopomorskie'],
	['Myślibórz', 'myśliborski', 'zachodniopomorskie'],
	['Łobez', 'łobeski', 'zachodniopomorskie'],
	['Trzebiatów', 'gryficki', 'zachodniopomorskie'],
	['Kamień Pomorski', 'kamieński', 'zachodniopomorskie'],
	['Połczyn-Zdrój', 'świdwiński', 'zachodniopomorskie'],
	['Chojna', 'gryfiński', 'zachodniopomorskie'],
	['Czaplinek', 'drawski', 'zachodniopomorskie'],
	['Sianów', 'koszaliński', 'zachodniopomorskie'],
	['Karlino', 'białogardzki', 'zachodniopomorskie'],
	['Międzyzdroje', 'kamieński', 'zachodniopomorskie'],
	['Borne Sulinowo', 'szczecinecki', 'zachodniopomorskie'],
	['Wolin', 'kamieński', 'zachodniopomorskie'],
	['Kalisz Pomorski', 'drawski', 'zachodniopomorskie'],
	['Resko', 'łobeski', 'zachodniopomorskie'],
	['Bobolice', 'koszaliński', 'zachodniopomorskie'],
	['Płoty', 'gryficki', 'zachodniopomorskie'],
	['Lipiany', 'pyrzycki', 'zachodniopomorskie'],
	['Barwice', 'szczecinecki', 'zachodniopomorskie'],
	['Mieszkowice', 'gryfiński', 'zachodniopomorskie'],
	['Maszewo', 'goleniowski', 'zachodniopomorskie'],
	['Chociwel', 'stargardzki', 'zachodniopomorskie'],
	['Mirosławiec', 'wałecki', 'zachodniopomorskie'],
	['Mielno', 'koszaliński', 'zachodniopomorskie'],
	['Polanów', 'koszaliński', 'zachodniopomorskie'],
	['Recz', 'choszczeński', 'zachodniopomorskie'],
	['Węgorzyno', 'łobeski', 'zachodniopomorskie'],
	['Dziwnów', 'kamieński', 'zachodniopomorskie'],
	['Golczewo', 'kamieński', 'zachodniopomorskie'],
	['Pełczyce', 'choszczeński', 'zachodniopomorskie'],
	['Tychowo', 'białogardzki', 'zachodniopomorskie'],
	['Stepnica', 'goleniowski', 'zachodniopomorskie'],
	['Gościno', 'kołobrzeski', 'zachodniopomorskie'],
	['Człopa', 'wałecki', 'zachodniopomorskie'],
	['Dobra', 'łobeski', 'zachodniopomorskie'],
	['Drawno', 'choszczeński', 'zachodniopomorskie'],
	['Trzcińsko-Zdrój', 'gryfiński', 'zachodniopomorskie'],
	['Dobrzany', 'stargardzki', 'zachodniopomorskie'],
	['Biały Bór', 'szczecinecki', 'zachodniopomorskie'],
	['Ińsko', 'stargardzki', 'zachodniopomorskie'],
	['Tuczno', 'wałecki', 'zachodniopomorskie'],
	['Moryń', 'gryfiński', 'zachodniopomorskie'],
	['Cedynia', 'gryfiński', 'zachodniopomorskie'],
	['Suchań', 'stargardzki', 'zachodniopomorskie'],
	['Nowe Warpno', 'policki', 'zachodniopomorskie'],
];

export const miastoWojewództwo: [string, string][] = cityDataList.map(([m, p, w]) => [m, w]);

export const szkoły: [string, string][] = [
	['ALOPB', 'Akademickie Liceum Ogólnokształcące Politechniki Białostockiej'],
	['I LO', 'I Liceum Ogólnokształcące im. Adama Mickiewicza'],
	['II LO', 'II Liceum Ogólnokształcące im. księżnej Anny z Sapiehów Jabłonowskiej'],
	['III LO', 'III Liceum Ogólnokształcące im. Krzysztofa Kamila Baczyńskiego'],
];

export interface Książki {
	wymagane: string[];
	opcjonalne: string[];
}

export interface KsiążkiSzkoły {
	książki: Książki;
	profile: {
		nazwa: string;
		opis: string;
		książki: Książki;
	}[];
	języki: {
		nazwa: string;
		książki: Książki;
	}[];
}

let i = 0;
const books = await db.book.findMany();

function randomBooks() {
	const j = i;
	i += 2 + Math.floor(Math.random() * 3);
	return books.slice(j, i).map((book) => book.id);
}

export const data: KsiążkiSzkoły = {
	książki: {
		wymagane: randomBooks(),
		opcjonalne: randomBooks(),
	},
	profile: [
		{
			nazwa: 'Przemysł przyszłości',
			opis: 'Matematyka, fizyka, informatyka',
			książki: {
				wymagane: randomBooks(),
				opcjonalne: randomBooks(),
			},
		},
		{
			nazwa: 'Programowanie',
			opis: 'Matematyka, informatyka, język angielski',
			książki: {
				wymagane: randomBooks(),
				opcjonalne: randomBooks(),
			},
		},
		{
			nazwa: 'Architektura i budownictwo',
			opis: 'Matematyka, fizyka, geografia',
			książki: {
				wymagane: randomBooks(),
				opcjonalne: randomBooks(),
			},
		},
	],
	języki: [
		{
			nazwa: 'Niemiecki',
			książki: {
				wymagane: randomBooks(),
				opcjonalne: randomBooks(),
			},
		},
		{
			nazwa: 'Rosyjski',
			książki: {
				wymagane: randomBooks(),
				opcjonalne: randomBooks(),
			},
		},
	],
};
